import type { Scheme } from "./schemes";
import { CENTRAL_SCHEMES } from "./schemes-data/central-schemes";
import { STATE_SCHEMES } from "./schemes-data/state-schemes";

const BASE_SCHEMES: Scheme[] = [
  {
    id: "sch-pm-kisan",
    slug: "pm-kisan",
    name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    category: "Agriculture",
    state: null,
    ministry: "Ministry of Agriculture & Farmers Welfare",
    department: "Department of Agriculture and Farmers Welfare",
    short_description:
      "Income support of ₹6,000 per year in three equal instalments to all landholding farmer families across India.",
    benefits:
      "₹6,000 per year directly transferred to bank account in 3 instalments of ₹2,000 each.",
    documents: [
      "Aadhaar card",
      "Land ownership records (ROR/Khatauni)",
      "Bank passbook",
      "Mobile number linked with Aadhaar",
    ],
    apply_url: "https://pmkisan.gov.in/",
    official_website: "https://pmkisan.gov.in/",
    official_source_url: "https://pmkisan.gov.in/",
    tags: ["farmer", "agriculture", "dbt", "central", "income-support"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["farmer"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "rural",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Farmer Income Support"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary: "All landholding farmer families with cultivable land in their names.",
    student_required: false,
    farmer_required: true,
    land_ownership_required: true,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ayushman-bharat",
    slug: "ayushman-bharat-pmjay",
    name: "Ayushman Bharat PM-JAY",
    category: "Healthcare",
    state: null,
    ministry: "Ministry of Health & Family Welfare",
    department: "National Health Authority",
    short_description:
      "World's largest government-funded healthcare assurance scheme offering ₹5 lakh cashless cover per family per year for secondary and tertiary hospitalisation.",
    benefits:
      "₹5,00,000 per family per year for cashless inpatient treatment at empanelled public and private hospitals nationwide.",
    documents: ["Aadhaar card", "Ration card", "PM-JAY golden card / Ayushman card"],
    apply_url: "https://beneficiary.nha.gov.in/",
    official_website: "https://pmjay.gov.in/",
    official_source_url: "https://pmjay.gov.in/",
    tags: ["health", "hospitalisation", "insurance", "cashless", "central"],
    min_age: null,
    max_age: null,
    gender: "any",
    max_annual_income: 250000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Health Insurance"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Bottom 40% vulnerable population identified via SECC database and state entitlement lists.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmay-g",
    slug: "pm-awas-yojana",
    name: "Pradhan Mantri Awas Yojana (PMAY)",
    category: "Housing",
    state: null,
    ministry: "Ministry of Housing and Urban Affairs",
    department: "Department of Rural Development / Housing",
    short_description:
      "Financial assistance to poor and homeless families in rural and urban areas for building a pucca house with basic amenities.",
    benefits:
      "Financial grant up to ₹1,30,000 for rural house construction, and interest subsidy up to ₹2.67 lakh for urban homes.",
    documents: [
      "Aadhaar card",
      "Bank account details",
      "Income certificate",
      "Affidavit of not owning a pucca house",
    ],
    apply_url: "https://pmaymis.gov.in/",
    official_website: "https://pmaymis.gov.in/",
    official_source_url: "https://pmaymis.gov.in/",
    tags: ["housing", "pucca-house", "rural", "urban", "central"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: 300000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Affordable Housing"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Homeless families or those living in kutcha/dilapidated houses not owning a pucca home anywhere in India.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pm-svanidhi",
    slug: "pm-svanidhi",
    name: "PM Street Vendor's AtmaNirbhar Nidhi (PM-SVANidhi)",
    category: "Livelihood",
    state: null,
    ministry: "Ministry of Housing and Urban Affairs",
    department: "Urban Livelihoods Division",
    short_description:
      "Collateral-free working capital loan up to ₹50,000 with 7% interest subsidy to help street vendors resume and grow businesses.",
    benefits:
      "First tranche loan of ₹10,000, progressing to ₹20,000 and ₹50,000 upon timely repayment, plus cashback up to ₹1,200/year on digital transactions.",
    documents: ["Aadhaar card", "Vending Certificate / Urban Local Body ID Card", "Bank passbook"],
    apply_url: "https://pmsvanidhi.mohua.gov.in/",
    official_website: "https://pmsvanidhi.mohua.gov.in/",
    official_source_url: "https://pmsvanidhi.mohua.gov.in/",
    tags: ["street-vendor", "micro-loan", "urban", "business", "central"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["street-vendor", "labour", "self-employed"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "urban",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Micro Credit"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary: "Street vendors engaged in vending in urban areas.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pm-mudra",
    slug: "pm-mudra-yojana",
    name: "Pradhan Mantri MUDRA Yojana (PMMY)",
    category: "Business",
    state: null,
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    short_description:
      "Collateral-free institutional credit up to ₹20 lakh to non-corporate, non-farm small and micro enterprises across Shishu, Kishore and Tarun categories.",
    benefits:
      "Loans: Shishu (up to ₹50,000), Kishore (₹50,000 to ₹5 lakh), Tarun (₹5 lakh to ₹20 lakh) at competitive interest rates without collateral.",
    documents: [
      "Aadhaar card",
      "PAN card",
      "Business address proof",
      "Bank statements (past 6 months)",
      "Project report/quotation",
    ],
    apply_url: "https://www.mudra.org.in/",
    official_website: "https://www.mudra.org.in/",
    official_source_url: "https://www.mudra.org.in/",
    tags: ["business", "loan", "msme", "entrepreneur", "central"],
    min_age: 18,
    max_age: 65,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["entrepreneur", "self-employed", "business", "street-vendor"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Enterprise Loans"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Any Indian citizen who has a business plan for a non-farm sector income generating activity.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-sukanya-samriddhi",
    slug: "sukanya-samriddhi-yojana",
    name: "Sukanya Samriddhi Yojana (SSY)",
    category: "Girl Child",
    state: null,
    ministry: "Ministry of Finance",
    department: "Department of Posts / Economic Affairs",
    short_description:
      "High-interest, tax-free small deposit savings scheme for girl children under Beti Bachao Beti Padhao campaign.",
    benefits:
      "High government-backed interest rate (8.2%+ p.a.), Section 80C tax deduction, tax-free maturity and partial withdrawal for higher education.",
    documents: [
      "Girl child birth certificate",
      "Parent/guardian Aadhaar and PAN",
      "Address proof",
      "Passport size photograph",
    ],
    apply_url: "https://www.indiapost.gov.in/",
    official_website: "https://www.indiapost.gov.in/",
    official_source_url: "https://www.indiapost.gov.in/",
    tags: ["girl-child", "savings", "tax-free", "education", "central"],
    min_age: 0,
    max_age: 10,
    gender: "female",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Girl Child Financial Security"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Girl child resident of India aged below 10 years at account opening (max 2 accounts per family).",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-atal-pension",
    slug: "atal-pension-yojana",
    name: "Atal Pension Yojana (APY)",
    category: "Pension",
    state: null,
    ministry: "Ministry of Finance",
    department: "Pension Fund Regulatory and Development Authority (PFRDA)",
    short_description:
      "Guaranteed monthly pension of ₹1,000 to ₹5,000 from age 60 for workers in the unorganised sector.",
    benefits:
      "Guaranteed monthly pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000 or ₹5,000 after attaining age 60; spouse receives same pension after subscriber demise.",
    documents: ["Aadhaar card", "Active bank savings account", "Mobile number"],
    apply_url: "https://enps.nsdl.com/eNPS/ApySubRegistration.html",
    official_website: "https://www.npscra.nsdl.co.in/",
    official_source_url: "https://www.npscra.nsdl.co.in/",
    tags: ["pension", "unorganised-worker", "social-security", "retirement", "central"],
    min_age: 18,
    max_age: 40,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["labour", "unorganised-worker", "self-employed", "farmer", "any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    available_states: [],
    districts: [],
    subcategories: ["Old Age Pension"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-01T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Any Indian citizen between 18 and 40 years holding a savings bank account who is not an income tax payer.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: false,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-as-orunodoi",
    slug: "as-orunodoi",
    name: "Orunodoi Scheme",
    category: "Women & Welfare",
    state: "Assam",
    ministry: "Govt. of Assam",
    department: "Finance Department, Assam",
    short_description:
      "Monthly financial assistance of ₹1,250 to women from economically weaker families in Assam.",
    benefits: "₹1,250/month direct benefit transfer to woman head of family.",
    documents: ["Aadhaar", "Bank details", "Ration card", "Residence proof"],
    apply_url: "https://orunodoi.assam.gov.in/",
    official_website: "https://orunodoi.assam.gov.in/",
    official_source_url: "https://orunodoi.assam.gov.in/",
    tags: ["women", "assam", "dbt"],
    min_age: 18,
    max_age: null,
    gender: "female",
    max_annual_income: 200000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Assam"],
    districts: [],
    subcategories: ["Women Welfare"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Women permanent residents of Assam with family annual income under ₹2 lakh.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-cg-mahtari-vandan",
    slug: "cg-mahtari-vandan",
    name: "Mahtari Vandan Yojana",
    category: "Women & Welfare",
    state: "Chhattisgarh",
    ministry: "Govt. of Chhattisgarh",
    department: "Women and Child Development Department",
    short_description:
      "₹1,000 monthly to married women in Chhattisgarh aged 21+ for financial independence.",
    benefits: "₹12,000/year direct benefit transfer (₹1,000 per month).",
    documents: ["Aadhaar", "Marriage certificate", "Bank passbook", "Voter ID"],
    apply_url: "https://mahtarivandan.cgstate.gov.in/",
    official_website: "https://mahtarivandan.cgstate.gov.in/",
    official_source_url: "https://mahtarivandan.cgstate.gov.in/",
    tags: ["women", "chhattisgarh", "dbt"],
    min_age: 21,
    max_age: 60,
    gender: "female",
    max_annual_income: 250000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Chhattisgarh"],
    districts: [],
    subcategories: ["Women Welfare"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary: "Married women resident of Chhattisgarh aged 21-60.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: "married",
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ka-shakti",
    slug: "ka-shakti",
    name: "Shakti Scheme (Free Bus Travel)",
    category: "Women & Welfare",
    state: "Karnataka",
    ministry: "Govt. of Karnataka",
    department: "Transport Department",
    short_description:
      "Free travel for women in Karnataka state-run non-premium buses across the state.",
    benefits:
      "100% free bus travel across Karnataka on KSRTC, BMTC, NWKRTC, and KKRTC state transport buses.",
    documents: ["Aadhaar", "Karnataka residence proof"],
    apply_url: "https://ksrtc.in/",
    official_website: "https://ksrtc.in/",
    official_source_url: "https://ksrtc.in/",
    tags: ["women", "karnataka", "transport"],
    min_age: 18,
    max_age: null,
    gender: "female",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Karnataka"],
    districts: [],
    subcategories: ["Mobility & Transport"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary: "All women and transgender persons residing in Karnataka.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ka-gruha-jyothi",
    slug: "ka-gruha-jyothi",
    name: "Gruha Jyothi",
    category: "Utilities",
    state: "Karnataka",
    ministry: "Govt of Karnataka",
    department: "Energy Department",
    short_description: "Free electricity up to 200 units per month for Karnataka households.",
    benefits: "Zero electricity bill up to 200 units of monthly household power consumption.",
    documents: ["Aadhaar", "Electricity bill", "Customer ID"],
    apply_url: "https://sevasindhugs.karnataka.gov.in/",
    official_website: "https://sevasindhugs.karnataka.gov.in/",
    official_source_url: "https://sevasindhugs.karnataka.gov.in/",
    tags: ["utilities", "household", "electricity", "karnataka"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Karnataka"],
    districts: [],
    subcategories: ["Power Subsidy"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-08-04T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Domestic electricity consumers in Karnataka with average consumption under 200 units/month.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ap-talliki-vandanam",
    slug: "ap-thalliki-vandanam",
    name: "Talliki Vandanam (replaces Amma Vodi)",
    category: "Education",
    state: "Andhra Pradesh",
    ministry: "Govt of Andhra Pradesh",
    department: "School Education Department, Government of Andhra Pradesh",
    short_description:
      "Direct benefit transfer of ₹15,000 per year per child to mother or guardian of eligible students studying in Classes I to XII in Andhra Pradesh.",
    benefits: "₹15,000 per annum per child credited to the mother/guardian bank account.",
    documents: [
      "Aadhaar of mother/guardian and child",
      "Student admission details / school record",
      "Bank account passbook",
      "Rice (ration) card",
      "Attendance record",
    ],
    apply_url: "https://thallikivandanam.org/",
    official_website: "https://thallikivandanam.org/",
    official_source_url: "https://thallikivandanam.org/",
    tags: ["education", "school", "mother", "dbt", "andhra pradesh"],
    min_age: null,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: ["primary", "secondary", "higher-secondary"],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Andhra Pradesh"],
    districts: [],
    subcategories: ["School Education"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-15T00:00:00Z",
    last_updated: "2026-09-15T00:00:00Z",
    created_at: "2026-09-15T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Mother/guardian of a child studying Class I to XII in a recognised school or junior college in Andhra Pradesh.",
    student_required: true,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ap-dr-ntr-vaidya-seva",
    slug: "ap-dr-ntr-vaidya-seva",
    name: "Dr NTR Vaidya Seva",
    category: "Healthcare",
    state: "Andhra Pradesh",
    ministry: "Govt of Andhra Pradesh",
    department: "Dr NTR Vaidya Seva Trust, Government of Andhra Pradesh",
    short_description:
      "Cashless health cover for families in Andhra Pradesh at empanelled government and private hospitals across thousands of listed medical treatments.",
    benefits:
      "Cashless hospital treatment for listed procedures under an annual family floater cover.",
    documents: [
      "Rice (white) ration card",
      "Aadhaar card",
      "Aarogyasri / health card",
      "Address proof",
    ],
    apply_url: "https://drntrvaidyaseva.ap.gov.in/",
    official_website: "https://drntrvaidyaseva.ap.gov.in/",
    official_source_url: "https://drntrvaidyaseva.ap.gov.in/",
    tags: ["health", "insurance", "hospital", "aarogyasri", "andhra pradesh"],
    min_age: null,
    max_age: null,
    gender: "any",
    max_annual_income: 500000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Andhra Pradesh"],
    districts: [],
    subcategories: ["Health Insurance"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-15T00:00:00Z",
    last_updated: "2026-09-15T00:00:00Z",
    created_at: "2026-09-15T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Households in Andhra Pradesh holding a rice/ration card, or with annual household income up to ₹5 lakh.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ts-rythu-bandhu",
    slug: "ts-rythu-bandhu",
    name: "Rythu Bandhu",
    category: "Agriculture",
    state: "Telangana",
    ministry: "Govt of Telangana",
    department: "Agriculture Department",
    short_description: "Investment support per acre per season for Telangana farmers.",
    benefits: "₹5,000 per acre per season investment assistance to farmers.",
    documents: ["Pattadar passbook", "Aadhaar", "Bank passbook"],
    apply_url: "https://rythubandhu.telangana.gov.in/",
    official_website: "https://rythubandhu.telangana.gov.in/",
    official_source_url: "https://rythubandhu.telangana.gov.in/",
    tags: ["farmer", "agriculture", "telangana"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["farmer"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "rural",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Telangana"],
    districts: [],
    subcategories: ["Farmer Investment Support"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-08-04T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary: "Land-owning farmers in Telangana holding Pattadar passbooks.",
    student_required: false,
    farmer_required: true,
    land_ownership_required: true,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-up-cm-abhyudaya",
    slug: "up-cm-abhyudaya",
    name: "Mukhyamantri Abhyudaya Yojana",
    category: "Education",
    state: "Uttar Pradesh",
    ministry: "Govt. of Uttar Pradesh",
    department: "Social Welfare Department, UP",
    short_description:
      "Free coaching for civil services (UPSC/UPPSC), JEE, NEET, NDA, CDS and other competitive exams for UP students.",
    benefits:
      "100% free offline and online coaching, study material, digital tablets and mentorship by senior IAS/IPS officers.",
    documents: ["Aadhaar", "Class 12 marksheet", "Residence proof", "Income certificate"],
    apply_url: "https://abhyuday.up.gov.in/",
    official_website: "https://abhyuday.up.gov.in/",
    official_source_url: "https://abhyuday.up.gov.in/",
    tags: ["education", "uttar pradesh", "students", "coaching"],
    min_age: 17,
    max_age: 35,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["student", "unemployed", "any"],
    education_levels: ["higher-secondary", "diploma", "graduate", "postgraduate"],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Uttar Pradesh"],
    districts: [],
    subcategories: ["Competitive Exam Coaching"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Students and youths resident of Uttar Pradesh preparing for competitive exams.",
    student_required: true,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-kl-life-mission",
    slug: "kl-life-mission",
    name: "LIFE Mission Housing",
    category: "Housing",
    state: "Kerala",
    ministry: "Govt. of Kerala",
    department: "Local Self Government Department",
    short_description:
      "Complete house and livelihood security for landless and houseless families of Kerala.",
    benefits: "Fully built pucca house + land allocation in eligible cases.",
    documents: ["Aadhaar", "Ration card", "Residence proof"],
    apply_url: "https://life2020.kerala.gov.in/",
    official_website: "https://life2020.kerala.gov.in/",
    official_source_url: "https://life2020.kerala.gov.in/",
    tags: ["housing", "kerala"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: 200000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Kerala"],
    districts: [],
    subcategories: ["Affordable Housing"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Houseless and landless families residing in Kerala with family income under ₹2 lakh.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-hp-himcare",
    slug: "hp-himcare",
    name: "HIMCARE Health Insurance",
    category: "Healthcare",
    state: "Himachal Pradesh",
    ministry: "Govt. of Himachal Pradesh",
    department: "Department of Health & Family Welfare",
    short_description:
      "Cashless health cover of ₹5 lakh/family/year for Himachal Pradesh residents not covered under Ayushman Bharat.",
    benefits: "₹5 lakh/year cashless medical treatment across empanelled hospitals.",
    documents: ["Aadhaar", "Himachali bonafide certificate", "Ration card"],
    apply_url: "https://hpsbys.in/",
    official_website: "https://hpsbys.in/",
    official_source_url: "https://hpsbys.in/",
    tags: ["health", "himachal", "insurance"],
    min_age: null,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Himachal Pradesh"],
    districts: [],
    subcategories: ["Health Insurance"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary: "Himachal Pradesh residents not covered under Ayushman Bharat (PM-JAY).",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-jh-maiya-samman",
    slug: "jh-mukhyamantri-maiya-samman",
    name: "Mukhyamantri Maiya Samman Yojana",
    category: "Women & Welfare",
    state: "Jharkhand",
    ministry: "Govt. of Jharkhand",
    department: "Women, Child Development and Social Security",
    short_description:
      "₹2,500 monthly assistance to women aged 18-50 belonging to poor families in Jharkhand.",
    benefits: "₹2,500/month direct benefit transfer to eligible women.",
    documents: ["Aadhaar", "Bank passbook", "Ration card", "Residence proof"],
    apply_url: "https://mmmsy.jharkhand.gov.in/",
    official_website: "https://mmmsy.jharkhand.gov.in/",
    official_source_url: "https://mmmsy.jharkhand.gov.in/",
    tags: ["women", "jharkhand", "dbt"],
    min_age: 18,
    max_age: 50,
    gender: "female",
    max_annual_income: 250000,
    min_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    bpl_only: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Jharkhand"],
    districts: [],
    subcategories: ["Women Welfare"],
    verification_status: "Verified",
    scheme_status: "Active",
    last_verified: "2026-09-01T00:00:00Z",
    last_updated: "2026-09-01T00:00:00Z",
    created_at: "2026-07-27T00:00:00Z",
    eligibility_rules: null,
    eligibility_summary:
      "Women aged 18-50 resident of Jharkhand from economically weaker families.",
    student_required: false,
    farmer_required: false,
    land_ownership_required: false,
    employment_status: null,
    marital_status: null,
    widow_required: false,
    senior_citizen_required: false,
    minority_required: false,
    residency_required: true,
    residency_years: null,
    link_status: "ok",
    link_checked_at: "2026-09-15T00:00:00Z",
    link_http_status: 200,
    link_fail_count: 0,
  },
];

const schemeMap = new Map<string, Scheme>();
for (const s of [...BASE_SCHEMES, ...CENTRAL_SCHEMES, ...STATE_SCHEMES]) {
  const key = s.slug || s.id;
  if (!schemeMap.has(key)) {
    schemeMap.set(key, s);
  }
}

export const DEFAULT_SCHEMES: Scheme[] = Array.from(schemeMap.values());
