import type { Scheme } from "../schemes";

export const CENTRAL_SCHEMES: Scheme[] = [
  {
    id: "sch-pm-surya-ghar",
    slug: "pm-surya-ghar-muft-bijli-yojana",
    name: "PM Surya Ghar: Muft Bijli Yojana",
    category: "Energy & Housing",
    state: null,
    ministry: "Ministry of New and Renewable Energy",
    department: "Grid Connected Solar Rooftop Division",
    short_description:
      "Up to ₹78,000 direct subsidy for rooftop solar installation and up to 300 units of free electricity every month for 1 crore households.",
    benefits:
      "Direct subsidy of ₹30,000 for 1 kW, ₹60,000 for 2 kW, and ₹78,000 for 3 kW and above rooftop solar systems. Save ₹15,000–₹25,000 annually on electricity bills.",
    documents: [
      "Aadhaar card",
      "Recent electricity bill",
      "Bank passbook",
      "Proof of roof ownership / electricity connection",
    ],
    apply_url: "https://pmsuryaghar.gov.in/",
    official_website: "https://pmsuryaghar.gov.in/",
    official_source_url: "https://pmsuryaghar.gov.in/",
    tags: ["solar", "free-electricity", "energy", "subsidy", "central", "all-citizens"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmgkay-ration",
    slug: "pm-garib-kalyan-anna-yojana",
    name: "Pradhan Mantri Garib Kalyan Anna Yojana (PMGKAY)",
    category: "Food & Social Welfare",
    state: null,
    ministry: "Ministry of Consumer Affairs, Food and Public Distribution",
    department: "Department of Food and Public Distribution",
    short_description:
      "Free 5 kg foodgrains (rice/wheat) per person per month for all NFSA priority households and Antyodaya Anna Yojana (AAY) families across India.",
    benefits:
      "Completely free ration of 5 kg food grains per family member per month (35 kg per family for Antyodaya cards) through Fair Price Shops using One Nation One Ration Card.",
    documents: ["Ration Card (NFSA / AAY / PHH)", "Aadhaar Card of all family members"],
    apply_url: "https://nfsa.gov.in/",
    official_website: "https://nfsa.gov.in/",
    official_source_url: "https://nfsa.gov.in/",
    tags: ["food-security", "ration", "bpl", "free-grains", "central", "dbt"],
    min_age: 0,
    max_age: null,
    gender: "any",
    max_annual_income: 300000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pm-vishwakarma",
    slug: "pm-vishwakarma-yojana",
    name: "PM Vishwakarma Scheme",
    category: "Employment & Skilling",
    state: null,
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "MSME Development",
    short_description:
      "Recognition, skill upgradation with ₹500/day stipend, ₹15,000 toolkit e-voucher, and collateral-free enterprise loans up to ₹3 Lakh at 5% interest for traditional artisans.",
    benefits:
      "PM Vishwakarma certificate & ID, basic and advanced skill training, ₹15,000 digital toolkit voucher, ₹1 Lakh loan (first tranche) and ₹2 Lakh loan (second tranche) at concessional 5% interest rate.",
    documents: [
      "Aadhaar Card",
      "Mobile number linked with Aadhaar",
      "Bank passbook",
      "Artisan trade proof / self-declaration",
    ],
    apply_url: "https://pmvishwakarma.gov.in/",
    official_website: "https://pmvishwakarma.gov.in/",
    official_source_url: "https://pmvishwakarma.gov.in/",
    tags: ["artisan", "craftsman", "self-employed", "skills", "collateral-free-loan", "msme"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: [
      "labour",
      "unorganised-worker",
      "self-employed",
      "entrepreneur",
      "business",
      "any",
    ],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pm-ujjwala",
    slug: "pradhan-mantri-ujjwala-yojana",
    name: "Pradhan Mantri Ujjwala Yojana (PMUY 2.0)",
    category: "Women & Energy",
    state: null,
    ministry: "Ministry of Petroleum and Natural Gas",
    department: "LPG Division",
    short_description:
      "Deposit-free LPG cylinder connection with first refill and stove free of cost, plus ongoing targeted subsidy of ₹300 per 14.2 kg domestic cylinder for women from poor households.",
    benefits:
      "Free LPG gas connection in the name of an adult woman of the family, free gas stove, first cylinder refill free, and direct bank account subsidy of ₹300 per cylinder for up to 12 refills a year.",
    documents: [
      "Aadhaar card of applicant woman",
      "Ration card / Family document",
      "Bank account passbook",
      "Proof of address",
    ],
    apply_url: "https://pmuy.gov.in/",
    official_website: "https://pmuy.gov.in/",
    official_source_url: "https://pmuy.gov.in/",
    tags: ["women", "lpg", "clean-cooking", "energy", "central", "subsidy"],
    min_age: 18,
    max_age: null,
    gender: "female",
    max_annual_income: 250000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmjjby",
    slug: "pm-jeevan-jyoti-bima-yojana",
    name: "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
    category: "Insurance & Security",
    state: null,
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    short_description:
      "₹2 Lakh renewable life insurance cover for death due to any cause at an affordable annual premium of only ₹436 for all citizens aged 18 to 50.",
    benefits:
      "₹2,00,000 paid to the nominee upon demise of the insured person due to any illness, accident, or natural cause. Auto-debited from bank/post office account.",
    documents: ["Aadhaar Card", "Savings Bank / Post Office Account with auto-debit consent"],
    apply_url: "https://www.jansuraksha.gov.in/",
    official_website: "https://www.jansuraksha.gov.in/",
    official_source_url: "https://www.jansuraksha.gov.in/",
    tags: ["life-insurance", "security", "financial-inclusion", "central", "affordable"],
    min_age: 18,
    max_age: 50,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmsby",
    slug: "pm-suraksha-bima-yojana",
    name: "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
    category: "Insurance & Security",
    state: null,
    ministry: "Ministry of Finance",
    department: "Department of Financial Services",
    short_description:
      "₹2 Lakh accidental death and full permanent disability cover for just ₹20 per year for all bank account holders aged 18 to 70.",
    benefits:
      "₹2,00,000 for accidental death or total permanent disability; ₹1,00,000 for partial permanent disability. Premium of just ₹20/year auto-debited annually.",
    documents: ["Aadhaar card", "Bank / Post Office savings account"],
    apply_url: "https://www.jansuraksha.gov.in/",
    official_website: "https://www.jansuraksha.gov.in/",
    official_source_url: "https://www.jansuraksha.gov.in/",
    tags: ["accident-insurance", "insurance", "security", "low-cost", "central"],
    min_age: 18,
    max_age: 70,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmmvy",
    slug: "pm-matru-vandana-yojana",
    name: "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
    category: "Women & Child Care",
    state: null,
    ministry: "Ministry of Women and Child Development",
    department: "Maternal Health & Nutrition",
    short_description:
      "Direct cash maternity incentive of ₹5,000 for the first child and ₹6,000 for the second child (if girl) to pregnant women and lactating mothers.",
    benefits:
      "Direct Benefit Transfer to woman's bank account in instalments upon early pregnancy registration, ANC checkups, and institutional child birth & vaccination.",
    documents: [
      "Mother and Child Protection (MCP) card",
      "Aadhaar of mother and husband",
      "Bank passbook linked with Aadhaar",
    ],
    apply_url: "https://pmmvy.wcd.gov.in/",
    official_website: "https://pmmvy.wcd.gov.in/",
    official_source_url: "https://pmmvy.wcd.gov.in/",
    tags: ["women", "maternity", "health", "infant-care", "dbt", "central"],
    min_age: 19,
    max_age: 45,
    gender: "female",
    max_annual_income: 800000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmfby",
    slug: "pm-fasal-bima-yojana",
    name: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    category: "Agriculture",
    state: null,
    ministry: "Ministry of Agriculture & Farmers Welfare",
    department: "Credit and Insurance Division",
    short_description:
      "Comprehensive crop insurance shield against non-preventable natural calamities (drought, flood, unseasonal rains, pest attacks) with nominal premium rates of 1.5% to 2%.",
    benefits:
      "Full sum insured payout for localized calamities, post-harvest losses, and prevented sowing. Low farmer premium (2% Kharif, 1.5% Rabi, 5% commercial/horticultural crops); rest subsidized by Govt.",
    documents: [
      "Aadhaar card",
      "Land revenue records (RoR/Khatauni)",
      "Sowing certificate / crop declaration",
      "Bank passbook",
    ],
    apply_url: "https://pmfby.gov.in/",
    official_website: "https://pmfby.gov.in/",
    official_source_url: "https://pmfby.gov.in/",
    tags: ["agriculture", "crop-insurance", "farmers", "disaster-relief", "central"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["farmer"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "rural",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-kisan-credit-card",
    slug: "kisan-credit-card-scheme",
    name: "Kisan Credit Card (KCC) Scheme",
    category: "Agriculture & Finance",
    state: null,
    ministry: "Ministry of Agriculture & Farmers Welfare",
    department: "Department of Agriculture",
    short_description:
      "Concessional credit limit up to ₹3 Lakh at an effective interest rate of just 4% per annum for farmers, dairy owners, and fishermen with prompt repayment incentive.",
    benefits:
      "Flexible revolving credit card for crop cultivation, animal husbandry, fisheries, and post-harvest expenses with 3% prompt repayment subvention and ₹1.6 Lakh collateral-free limit.",
    documents: [
      "Aadhaar card",
      "Land ownership / lease records",
      "Passport size photograph",
      "No-dues certificate from local banks",
    ],
    apply_url: "https://fasalrin.gov.in/",
    official_website: "https://fasalrin.gov.in/",
    official_source_url: "https://fasalrin.gov.in/",
    tags: ["farmer", "credit", "low-interest", "kcc", "agriculture", "central"],
    min_age: 18,
    max_age: 75,
    gender: "any",
    max_annual_income: null,
    occupations: ["farmer"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "rural",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pm-internship",
    slug: "pm-internship-scheme",
    name: "Prime Minister's Internship Scheme (PMIS)",
    category: "Youth & Employment",
    state: null,
    ministry: "Ministry of Corporate Affairs",
    department: "Youth Employability Division",
    short_description:
      "12-month internship opportunities in India's top 500 companies with a monthly stipend of ₹5,000 plus ₹6,000 one-time grant for youth aged 21 to 24.",
    benefits:
      "Monthly stipend of ₹5,000 (₹4,500 by Govt + ₹500 CSR contribution), ₹6,000 one-time grant for incidentals, insurance coverage under PMJJBY/PMSBY, and corporate work experience.",
    documents: [
      "Aadhaar card",
      "Educational certificates (10th/12th/ITI/Diploma/Graduation)",
      "Bank passbook",
    ],
    apply_url: "https://www.myscheme.gov.in/schemes/pmis",
    official_website: "https://www.myscheme.gov.in/schemes/pmis",
    official_source_url: "https://www.myscheme.gov.in/schemes/pmis",
    tags: ["internship", "youth", "students", "unemployed", "stipend", "corporate", "central"],
    min_age: 21,
    max_age: 24,
    gender: "any",
    max_annual_income: 800000,
    occupations: ["student", "unemployed", "any"],
    education_levels: ["secondary", "higher-secondary", "diploma", "graduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmkvy",
    slug: "pm-kaushal-vikas-yojana",
    name: "Pradhan Mantri Kaushal Vikas Yojana 4.0 (PMKVY)",
    category: "Employment & Skilling",
    state: null,
    ministry: "Ministry of Skill Development and Entrepreneurship",
    department: "National Skill Development Corporation (NSDC)",
    short_description:
      "Free industry-aligned skill certification, on-job training in Industry 4.0 trades (AI, robotics, drones, electronics), and placement assistance with monetary reward.",
    benefits:
      "100% free technical and soft skill courses, recognized National Skills Qualifications Framework (NSQF) certificate, travel and assessment allowance, and job placement assistance.",
    documents: ["Aadhaar card", "Bank passbook", "School/college leaving certificate"],
    apply_url: "https://www.skillindiadigital.gov.in/",
    official_website: "https://www.skillindiadigital.gov.in/",
    official_source_url: "https://www.skillindiadigital.gov.in/",
    tags: ["skilling", "training", "youth", "certification", "jobs", "central"],
    min_age: 15,
    max_age: 45,
    gender: "any",
    max_annual_income: null,
    occupations: ["student", "unemployed", "labour", "unorganised-worker", "any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-pmegp",
    slug: "prime-ministers-employment-generation-programme",
    name: "Prime Minister's Employment Generation Programme (PMEGP)",
    category: "Business & Entrepreneurship",
    state: null,
    ministry: "Ministry of Micro, Small and Medium Enterprises",
    department: "Khadi and Village Industries Commission (KVIC)",
    short_description:
      "Bank-financed subsidy scheme providing up to ₹50 Lakh loan for manufacturing and ₹20 Lakh for service units with 15% to 35% government capital subsidy.",
    benefits:
      "Government subsidy of 15% (general urban), 25% (general rural or special category urban), and 35% (SC/ST/OBC/Women/Minority/Divyang/Rural). Own contribution only 5% to 10%.",
    documents: [
      "Aadhaar card",
      "Project proposal / DPR",
      "Educational qualification certificate",
      "Caste / Special category certificate (if applicable)",
    ],
    apply_url: "https://www.kviconline.gov.in/pmegpeportal/",
    official_website: "https://www.kviconline.gov.in/pmegpeportal/",
    official_source_url: "https://www.kviconline.gov.in/pmegpeportal/",
    tags: ["business", "entrepreneurship", "subsidy", "startup", "msme", "central"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["self-employed", "entrepreneur", "business", "unemployed", "any"],
    education_levels: ["secondary", "higher-secondary", "diploma", "graduate", "postgraduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-post-matric-scholarship",
    slug: "post-matric-scholarship-sc-st-obc",
    name: "Post-Matric Scholarship Scheme for SC / ST / OBC Students",
    category: "Education & Scholarships",
    state: null,
    ministry: "Ministry of Social Justice and Empowerment",
    department: "Department of Social Justice",
    short_description:
      "100% reimbursement of non-refundable tuition fees and monthly academic maintenance allowance for post-secondary and college students from marginalized communities.",
    benefits:
      "Full tuition fee reimbursement for college, polytechnic, engineering, medical, and university courses plus annual maintenance allowance up to ₹13,500 directly in student bank account.",
    documents: [
      "Aadhaar card",
      "Caste certificate (SC/ST/OBC)",
      "Income certificate (< ₹2.5 Lakh)",
      "Previous year mark sheet",
      "College fee receipt",
    ],
    apply_url: "https://scholarships.gov.in/",
    official_website: "https://scholarships.gov.in/",
    official_source_url: "https://scholarships.gov.in/",
    tags: ["scholarship", "students", "education", "college", "sc", "st", "obc", "central"],
    min_age: 15,
    max_age: 35,
    gender: "any",
    max_annual_income: 250000,
    occupations: ["student"],
    education_levels: ["higher-secondary", "diploma", "graduate", "postgraduate"],
    caste_categories: ["sc", "st", "obc", "ews", "minority"],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-nmmss",
    slug: "national-means-cum-merit-scholarship",
    name: "National Means-cum-Merit Scholarship Scheme (NMMSS)",
    category: "Education & Scholarships",
    state: null,
    ministry: "Ministry of Education",
    department: "Department of School Education & Literacy",
    short_description:
      "₹12,000 per year (₹1,000/month) scholarship for meritorious students of classes 9 to 12 studying in government and aided schools to arrest dropout rates.",
    benefits:
      "Direct Benefit Transfer of ₹12,000 annually into student's bank account for four consecutive years (Class 9 through 12).",
    documents: [
      "Aadhaar card",
      "Class 7/8 mark sheet (min 55% marks)",
      "Family income certificate (< ₹3.5 Lakh)",
      "School bonafide certificate",
    ],
    apply_url: "https://scholarships.gov.in/",
    official_website: "https://scholarships.gov.in/",
    official_source_url: "https://scholarships.gov.in/",
    tags: ["scholarship", "school", "students", "merit", "education", "central"],
    min_age: 13,
    max_age: 18,
    gender: "any",
    max_annual_income: 350000,
    occupations: ["student"],
    education_levels: ["primary", "secondary"],
    caste_categories: [],
    disability_required: false,
    is_popular: false,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-adip-divyangjan",
    slug: "adip-scheme-aids-appliances-disabled",
    name: "ADIP Scheme (Aids & Assistive Devices for Persons with Disabilities)",
    category: "Disability & Inclusion",
    state: null,
    ministry: "Ministry of Social Justice and Empowerment",
    department: "Department of Empowerment of Persons with Disabilities",
    short_description:
      "100% free modern, durable aids and assistive devices (motorized tricycles, wheelchairs, hearing aids, braille kits, prosthetics) for divyangjan.",
    benefits:
      "Full financial assistance for assistive appliances costing up to ₹15,000 (and up to ₹50,000 for high-end motorized devices/smart implants) distributed via nationwide ALIMCO camps.",
    documents: [
      "Aadhaar card",
      "Disability certificate (min 40% disability) or UDID card",
      "Income certificate (< ₹2.7 Lakh/yr for 100% subsidy)",
    ],
    apply_url: "https://adip.depwd.gov.in/",
    official_website: "https://adip.depwd.gov.in/",
    official_source_url: "https://adip.depwd.gov.in/",
    tags: ["disability", "divyang", "assistive-devices", "inclusion", "welfare", "central"],
    min_age: 0,
    max_age: null,
    gender: "any",
    max_annual_income: 360000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: true,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-eshram-welfare",
    slug: "e-shram-card-welfare-benefits",
    name: "e-Shram Social Security & Welfare Portal",
    category: "Labour & Social Security",
    state: null,
    ministry: "Ministry of Labour and Employment",
    department: "Unorganised Workers Division",
    short_description:
      "Universal national database of unorganised workers providing a 12-digit UAN, free accidental death/disability insurance of ₹2 Lakh, and seamless access to social security.",
    benefits:
      "Direct eligibility bridge for PM-SYM pension, PMSBY accidental insurance, disaster ex-gratia relief, and portability of food & maternity benefits across India.",
    documents: [
      "Aadhaar card linked with active mobile number",
      "Bank account passbook",
      "Occupation declaration",
    ],
    apply_url: "https://eshram.gov.in/",
    official_website: "https://eshram.gov.in/",
    official_source_url: "https://eshram.gov.in/",
    tags: ["labour", "unorganised-worker", "social-security", "insurance", "dbt", "central"],
    min_age: 16,
    max_age: 59,
    gender: "any",
    max_annual_income: null,
    occupations: [
      "labour",
      "unorganised-worker",
      "street-vendor",
      "farmer",
      "self-employed",
      "any",
    ],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-nsap-ignoaps",
    slug: "nsap-old-age-pension",
    name: "Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
    category: "Pensions & Senior Citizens",
    state: null,
    ministry: "Ministry of Rural Development",
    department: "National Social Assistance Programme",
    short_description:
      "Monthly social security pension for senior citizens aged 60+ belonging to below poverty line (BPL) families, supplemented with state top-ups.",
    benefits:
      "Direct monthly pension transferred to bank/post office account, supplemented by state governments for an effective total of ₹1,000 to ₹3,000/month.",
    documents: [
      "Aadhaar card",
      "Age proof / Birth certificate",
      "BPL ration card or BPL survey certificate",
      "Bank passbook",
    ],
    apply_url: "https://nsap.dord.gov.in/",
    official_website: "https://nsap.dord.gov.in/",
    official_source_url: "https://nsap.dord.gov.in/",
    tags: ["pension", "senior-citizen", "elderly", "bpl", "social-security", "central"],
    min_age: 60,
    max_age: null,
    gender: "any",
    max_annual_income: 200000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-mahila-samman-savings",
    slug: "mahila-samman-savings-certificate",
    name: "Mahila Samman Savings Certificate (MSSC)",
    category: "Women & Finance",
    state: null,
    ministry: "Ministry of Finance",
    department: "Department of Economic Affairs",
    short_description:
      "Government-backed high-yield 2-year fixed deposit scheme exclusively for women and girls offering an attractive 7.5% fixed interest compounded quarterly.",
    benefits:
      "Deposit up to ₹2,00,000 with sovereign government guarantee, guaranteed 7.5% interest, flexible partial withdrawal up to 40% after one year, and low minimum deposit of ₹1,000.",
    documents: ["Aadhaar card", "PAN card", "Recent passport photograph"],
    apply_url: "https://www.indiapost.gov.in/",
    official_website: "https://www.indiapost.gov.in/",
    official_source_url: "https://www.indiapost.gov.in/",
    tags: ["women", "savings", "investment", "fixed-deposit", "high-interest", "central"],
    min_age: 10,
    max_age: null,
    gender: "female",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: false,
    area_type: "any",
    government_level: "Central",
    scheme_scope: "CENTRAL_NATIONWIDE",
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
];
