import type { Scheme } from "../schemes";

export const STATE_SCHEMES: Scheme[] = [
  // --- Maharashtra ---
  {
    id: "sch-mh-ladki-bahin",
    slug: "mh-mukhyamantri-majhi-ladki-bahin",
    name: "Mukhyamantri Majhi Ladki Bahin Yojana",
    category: "Women & Welfare",
    state: "Maharashtra",
    ministry: "Govt. of Maharashtra",
    department: "Women and Child Development Department",
    short_description:
      "₹1,500 monthly direct financial assistance to married, widowed, divorced, destitute, and single women aged 21 to 65 years in Maharashtra.",
    benefits:
      "₹1,500 per month (₹18,000 annually) directly deposited into beneficiary's Aadhaar-linked bank account.",
    documents: [
      "Aadhaar card",
      "Maharashtra Domicile / 15-year Ration card",
      "Income certificate (< ₹2.5 Lakh)",
      "Bank passbook",
    ],
    apply_url: "https://ladkibahin.maharashtra.gov.in/",
    official_website: "https://ladkibahin.maharashtra.gov.in/",
    official_source_url: "https://ladkibahin.maharashtra.gov.in/",
    tags: ["women", "maharashtra", "dbt", "cash-support", "state"],
    min_age: 21,
    max_age: 65,
    gender: "female",
    max_annual_income: 250000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Maharashtra"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-mh-namo-shetkari",
    slug: "mh-namo-shetkari-mahasanman-nidhi",
    name: "Namo Shetkari Mahasanman Nidhi Yojana",
    category: "Agriculture",
    state: "Maharashtra",
    ministry: "Govt. of Maharashtra",
    department: "Agriculture Department",
    short_description:
      "Additional ₹6,000 per year directly to Maharashtra farmers on top of PM-KISAN, providing a combined ₹12,000 annual income support.",
    benefits:
      "₹6,000 per year in three equal instalments of ₹2,000 each credited directly to farmer bank accounts.",
    documents: ["PM-KISAN registration ID", "Aadhaar Card", "7/12 & 8A Land extracts"],
    apply_url: "https://krishi.maharashtra.gov.in/",
    official_website: "https://krishi.maharashtra.gov.in/",
    official_source_url: "https://krishi.maharashtra.gov.in/",
    tags: ["farmer", "maharashtra", "agriculture", "dbt", "income-support"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["farmer"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "rural",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Maharashtra"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-mh-mjpjay",
    slug: "mh-mahatma-jyotirao-phule-jan-arogya",
    name: "Mahatma Jyotirao Phule Jan Arogya Yojana (MJPJAY)",
    category: "Healthcare",
    state: "Maharashtra",
    ministry: "Govt. of Maharashtra",
    department: "Public Health Department",
    short_description:
      "Universal cashless health insurance coverage of up to ₹5 Lakh per family per year for all ration card holders and domicile residents in Maharashtra.",
    benefits:
      "100% cashless medical treatment and critical surgeries across 1,300+ empanelled government and private network hospitals.",
    documents: ["Ration card (Yellow / Orange / White)", "Aadhaar Card / Voter ID"],
    apply_url: "https://www.jeevandayee.gov.in/",
    official_website: "https://www.jeevandayee.gov.in/",
    official_source_url: "https://www.jeevandayee.gov.in/",
    tags: ["health", "cashless", "hospitalization", "maharashtra", "insurance"],
    min_age: 0,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Maharashtra"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Uttar Pradesh ---
  {
    id: "sch-up-kanya-sumangala",
    slug: "up-mukhyamantri-kanya-sumangala",
    name: "Mukhyamantri Kanya Sumangala Yojana",
    category: "Women & Child Care",
    state: "Uttar Pradesh",
    ministry: "Govt. of Uttar Pradesh",
    department: "Women and Child Development Department",
    short_description:
      "Enhanced financial grant of ₹25,000 provided in 6 stages from birth to college graduation for girl children in Uttar Pradesh.",
    benefits:
      "Stage-wise cash assistance: ₹5,000 at birth, ₹2,000 at full vaccination, ₹3,000 at Class 1 admission, ₹3,000 at Class 6, ₹5,000 at Class 9, and ₹7,000 on college admission.",
    documents: [
      "Aadhaar card of parents & girl",
      "Birth certificate",
      "UP Residence proof",
      "Income certificate (< ₹3 Lakh)",
      "School admission certificate",
    ],
    apply_url: "https://mksy.up.gov.in/",
    official_website: "https://mksy.up.gov.in/",
    official_source_url: "https://mksy.up.gov.in/",
    tags: ["girl-child", "education", "uttar-pradesh", "women", "dbt"],
    min_age: 0,
    max_age: 25,
    gender: "female",
    max_annual_income: 300000,
    occupations: ["student", "any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Uttar Pradesh"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-up-vridhavastha-pension",
    slug: "up-vridhavastha-pension-yojana",
    name: "UP Vridhavastha (Old Age) Pension Yojana",
    category: "Pensions & Senior Citizens",
    state: "Uttar Pradesh",
    ministry: "Govt. of Uttar Pradesh",
    department: "Social Welfare Department",
    short_description:
      "₹1,000 per month social security pension directly into the bank accounts of elderly citizens aged 60+ residing in Uttar Pradesh.",
    benefits:
      "Direct monthly benefit transfer of ₹1,000/month (₹3,000 quarterly) to senior citizens.",
    documents: [
      "Aadhaar card",
      "Age proof (min 60 years)",
      "Income certificate (< ₹46,080 rural, < ₹56,460 urban)",
      "Bank passbook",
    ],
    apply_url: "https://sspy-up.gov.in/",
    official_website: "https://sspy-up.gov.in/",
    official_source_url: "https://sspy-up.gov.in/",
    tags: ["pension", "senior-citizen", "uttar-pradesh", "elderly", "social-security"],
    min_age: 60,
    max_age: null,
    gender: "any",
    max_annual_income: 100000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Uttar Pradesh"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Tamil Nadu ---
  {
    id: "sch-tn-kmut",
    slug: "tn-kalaignar-magalir-urimai-thogai",
    name: "Kalaignar Magalir Urimai Thogai (KMUT)",
    category: "Women & Welfare",
    state: "Tamil Nadu",
    ministry: "Govt. of Tamil Nadu",
    department: "Special Programme Implementation Department",
    short_description:
      "₹1,000 monthly basic rights income directly transferred to women heads of eligible households across Tamil Nadu.",
    benefits:
      "₹1,000 per month (₹12,000/year) directly into woman head's bank account on the 15th of every month.",
    documents: [
      "Aadhaar card",
      "Smart / Digital Family Ration Card",
      "Electricity consumer number",
      "Bank passbook",
    ],
    apply_url: "https://kmut.tn.gov.in/",
    official_website: "https://kmut.tn.gov.in/",
    official_source_url: "https://kmut.tn.gov.in/",
    tags: ["women", "tamil-nadu", "basic-income", "dbt", "women-empowerment"],
    min_age: 21,
    max_age: null,
    gender: "female",
    max_annual_income: 250000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Tamil Nadu"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-tn-pudhumai-penn",
    slug: "tn-pudhumai-penn-scheme",
    name: "Pudhumai Penn Scheme (Higher Education Girl Student Incentive)",
    category: "Education & Scholarships",
    state: "Tamil Nadu",
    ministry: "Govt. of Tamil Nadu",
    department: "Social Welfare and Women Empowerment Department",
    short_description:
      "₹1,000 monthly financial grant directly into bank accounts of girl students who studied classes 6 to 12 in government schools till completion of undergraduate degree.",
    benefits:
      "Monthly cash assistance of ₹1,000 throughout diploma, undergraduate degree, or professional course duration.",
    documents: [
      "School study certificate (Class 6-12 in TN Govt school)",
      "College admission ID card / Bonafide",
      "Aadhaar card",
      "Bank passbook",
    ],
    apply_url: "https://www.pudhumaipenn.tn.gov.in/",
    official_website: "https://www.pudhumaipenn.tn.gov.in/",
    official_source_url: "https://www.pudhumaipenn.tn.gov.in/",
    tags: ["education", "girl-student", "tamil-nadu", "higher-education", "scholarship"],
    min_age: 17,
    max_age: 25,
    gender: "female",
    max_annual_income: null,
    occupations: ["student"],
    education_levels: ["higher-secondary", "diploma", "graduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Tamil Nadu"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Karnataka ---
  {
    id: "sch-ka-gruha-lakshmi",
    slug: "ka-gruha-lakshmi",
    name: "Gruha Lakshmi Scheme",
    category: "Women & Welfare",
    state: "Karnataka",
    ministry: "Govt. of Karnataka",
    department: "Women and Child Development Department",
    short_description:
      "₹2,000 monthly financial assistance directly into the bank accounts of women heads of BPL, APL, and Antyodaya households in Karnataka.",
    benefits:
      "₹2,000 monthly (₹24,000/year) direct benefit transfer to women heads of family to enhance financial independence.",
    documents: [
      "Aadhaar card of woman & husband",
      "Ration card (APL/BPL/AAY)",
      "Bank account linked with Aadhaar",
    ],
    apply_url: "https://sevasindhu.karnataka.gov.in/",
    official_website: "https://sevasindhu.karnataka.gov.in/",
    official_source_url: "https://sevasindhu.karnataka.gov.in/",
    tags: ["women", "karnataka", "dbt", "cash-assistance", "guarantee"],
    min_age: 18,
    max_age: null,
    gender: "female",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Karnataka"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ka-yuva-nidhi",
    slug: "ka-yuva-nidhi-scheme",
    name: "Yuva Nidhi Scheme (Unemployment Allowance)",
    category: "Youth & Employment",
    state: "Karnataka",
    ministry: "Govt. of Karnataka",
    department: "Skill Development, Entrepreneurship and Livelihood",
    short_description:
      "Monthly financial allowance of ₹3,000 for unemployed graduates and ₹1,500 for unemployed diploma holders for up to two years in Karnataka.",
    benefits:
      "₹3,000/month for degree holders and ₹1,500/month for diploma holders while preparing for jobs or skill upgradation.",
    documents: [
      "Graduation / Diploma completion certificate",
      "Karnataka Domicile certificate",
      "Aadhaar Card",
      "Bank passbook",
    ],
    apply_url: "https://sevasindhu.karnataka.gov.in/",
    official_website: "https://sevasindhu.karnataka.gov.in/",
    official_source_url: "https://sevasindhu.karnataka.gov.in/",
    tags: ["youth", "unemployed", "graduates", "stipend", "karnataka"],
    min_age: 20,
    max_age: 30,
    gender: "any",
    max_annual_income: null,
    occupations: ["unemployed", "student", "any"],
    education_levels: ["diploma", "graduate", "postgraduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Karnataka"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Telangana ---
  {
    id: "sch-ts-mahalakshmi",
    slug: "ts-mahalakshmi-scheme",
    name: "Mahalakshmi Scheme",
    category: "Women & Welfare",
    state: "Telangana",
    ministry: "Govt. of Telangana",
    department: "Women and Child Welfare Department",
    short_description:
      "₹2,500 monthly financial aid, 100% free TSRTC bus travel across Telangana, and subsidised LPG cylinder at ₹500 for women.",
    benefits:
      "Free bus travel in Palle Velugu & Express buses, monthly financial grant of ₹2,500, and domestic LPG gas cylinders at ₹500 for low-income families.",
    documents: [
      "Aadhaar card",
      "Telangana Ration card / Praja Palana acknowledgment",
      "Bank passbook",
    ],
    apply_url: "https://prajapalana.telangana.gov.in/",
    official_website: "https://prajapalana.telangana.gov.in/",
    official_source_url: "https://prajapalana.telangana.gov.in/",
    tags: ["women", "telangana", "free-bus", "lpg-subsidy", "dbt"],
    min_age: 18,
    max_age: null,
    gender: "female",
    max_annual_income: 250000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Telangana"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Andhra Pradesh ---
  {
    id: "sch-ap-cheyutha",
    slug: "ap-cheyutha-yojana",
    name: "YSR / AP Cheyutha Scheme",
    category: "Women & Livelihood",
    state: "Andhra Pradesh",
    ministry: "Govt. of Andhra Pradesh",
    department: "Social Welfare Department",
    short_description:
      "₹75,000 total financial assistance (₹18,750 per year for 4 years) for SC, ST, BC, and Minority women aged 45 to 60 for sustainable livelihoods.",
    benefits:
      "Annual cash grant of ₹18,750 directly into beneficiary account with technical and business tie-ups (Amul, ITC, P&G) to set up grocery, dairy, and retail units.",
    documents: [
      "Aadhaar card",
      "Caste certificate (SC/ST/BC/Minority)",
      "Age proof (45-60 yrs)",
      "Rice card / White ration card",
      "Bank passbook",
    ],
    apply_url: "https://gramawardsachivalayam.ap.gov.in/",
    official_website: "https://gramawardsachivalayam.ap.gov.in/",
    official_source_url: "https://gramawardsachivalayam.ap.gov.in/",
    tags: ["women", "andhra-pradesh", "sc", "st", "bc", "livelihood", "dbt"],
    min_age: 45,
    max_age: 60,
    gender: "female",
    max_annual_income: 150000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: ["sc", "st", "obc", "minority"],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Andhra Pradesh"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-ap-vidya-deevena",
    slug: "ap-jagananna-vidya-deevena",
    name: "Jagananna Vidya Deevena (Full Fee Reimbursement)",
    category: "Education & Scholarships",
    state: "Andhra Pradesh",
    ministry: "Govt. of Andhra Pradesh",
    department: "Higher Education Department",
    short_description:
      "100% full college tuition fee reimbursement directly credited to mother's account for ITI, Polytechnic, Degree, Engineering, and Pharmacy students.",
    benefits:
      "Full college fee reimbursement paid on quarterly basis directly into mother's bank account ensuring zero debt for higher education.",
    documents: [
      "College admission allotment order & ID",
      "Aadhaar card of student and mother",
      "Income certificate (< ₹2.5 Lakh)",
      "Mother's bank passbook",
    ],
    apply_url: "https://jnanabhumi.ap.gov.in/",
    official_website: "https://jnanabhumi.ap.gov.in/",
    official_source_url: "https://jnanabhumi.ap.gov.in/",
    tags: ["students", "college", "fee-reimbursement", "andhra-pradesh", "education"],
    min_age: 16,
    max_age: 30,
    gender: "any",
    max_annual_income: 250000,
    occupations: ["student"],
    education_levels: ["diploma", "graduate", "postgraduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Andhra Pradesh"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- West Bengal ---
  {
    id: "sch-wb-lakshmir-bhandar",
    slug: "wb-lakshmir-bhandar-scheme",
    name: "Lakshmir Bhandar Scheme",
    category: "Women & Welfare",
    state: "West Bengal",
    ministry: "Govt. of West Bengal",
    department: "Department of Women & Child Development and Social Welfare",
    short_description:
      "Assured monthly financial support of ₹1,000 for General category and ₹1,200 for SC/ST women aged 25 to 60 years in West Bengal.",
    benefits:
      "Direct bank transfer of ₹1,000/month (General) or ₹1,200/month (SC/ST) every month to the female head of household.",
    documents: [
      "Swasthya Sathi Card",
      "Aadhaar Card",
      "SC/ST Certificate (if applicable)",
      "Bank passbook",
    ],
    apply_url: "https://wb.gov.in/",
    official_website: "https://wb.gov.in/",
    official_source_url: "https://wb.gov.in/",
    tags: ["women", "west-bengal", "dbt", "basic-income", "financial-support"],
    min_age: 25,
    max_age: 60,
    gender: "female",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["West Bengal"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-wb-kanyashree",
    slug: "wb-kanyashree-prakalpa",
    name: "Kanyashree Prakalpa",
    category: "Education & Scholarships",
    state: "West Bengal",
    ministry: "Govt. of West Bengal",
    department: "Department of Women & Child Development",
    short_description:
      "Annual scholarship of ₹1,000 (K1) for schoolgirls aged 13-18 and one-time grant of ₹25,000 (K2) at age 18 to encourage higher education and prevent child marriage.",
    benefits:
      "Annual cash incentive of ₹1,000 during schooling and ₹25,000 one-time grant upon turning 18 if enrolled in higher education or vocational training and unmarried.",
    documents: [
      "School / College enrollment certificate",
      "Aadhaar card",
      "Birth certificate",
      "Unmarried declaration",
      "Bank passbook",
    ],
    apply_url: "https://www.wbkanyashree.gov.in/",
    official_website: "https://www.wbkanyashree.gov.in/",
    official_source_url: "https://www.wbkanyashree.gov.in/",
    tags: ["girls", "education", "scholarship", "west-bengal", "empowerment"],
    min_age: 13,
    max_age: 19,
    gender: "female",
    max_annual_income: null,
    occupations: ["student"],
    education_levels: ["secondary", "higher-secondary", "diploma", "graduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["West Bengal"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Bihar ---
  {
    id: "sch-br-kanya-utthan",
    slug: "br-mukhyamantri-kanya-utthan-yojana",
    name: "Mukhyamantri Kanya Utthan Yojana",
    category: "Women & Education",
    state: "Bihar",
    ministry: "Govt. of Bihar",
    department: "Education Department",
    short_description:
      "₹50,000 incentive on graduating college and ₹25,000 on passing 12th class for unmarried girl students in Bihar.",
    benefits:
      "₹50,000 direct bank transfer for every girl graduate from recognized universities in Bihar, plus ₹25,000 for unmarried girls passing intermediate examinations.",
    documents: [
      "Graduation / 12th Mark sheet & Admit Card",
      "Aadhaar card",
      "Bihar Residence certificate",
      "Bank passbook",
    ],
    apply_url: "https://medhasoft.bih.nic.in/",
    official_website: "https://medhasoft.bih.nic.in/",
    official_source_url: "https://medhasoft.bih.nic.in/",
    tags: ["women", "graduates", "education", "bihar", "dbt", "scholarship"],
    min_age: 17,
    max_age: 30,
    gender: "female",
    max_annual_income: null,
    occupations: ["student", "any"],
    education_levels: ["higher-secondary", "graduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Bihar"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-br-udyami-yojana",
    slug: "br-mukhyamantri-udyami-yojana",
    name: "Mukhyamantri Udyami Yojana",
    category: "Business & Entrepreneurship",
    state: "Bihar",
    ministry: "Govt. of Bihar",
    department: "Department of Industries",
    short_description:
      "Financial assistance up to ₹10 Lakh (₹5 Lakh grant + ₹5 Lakh interest-free loan) to set up manufacturing or service enterprises for youth and women in Bihar.",
    benefits:
      "50% non-repayable grant up to ₹5,00,000 and 50% interest-free loan (1% for general men) repayable in 84 monthly instalments with 3 months free project training.",
    documents: [
      "10+2 / Intermediate or ITI certificate",
      "Bihar Domicile certificate",
      "Aadhaar Card & PAN Card",
      "Cancelled cheque / Bank passbook",
    ],
    apply_url: "https://udyami.bihar.gov.in/",
    official_website: "https://udyami.bihar.gov.in/",
    official_source_url: "https://udyami.bihar.gov.in/",
    tags: ["entrepreneurship", "business", "grant", "bihar", "startup", "msme"],
    min_age: 18,
    max_age: 50,
    gender: "any",
    max_annual_income: null,
    occupations: ["self-employed", "entrepreneur", "business", "unemployed", "any"],
    education_levels: ["higher-secondary", "diploma", "graduate", "postgraduate"],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Bihar"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Rajasthan ---
  {
    id: "sch-rj-maay-health",
    slug: "rj-mukhyamantri-ayushman-arogya",
    name: "Mukhyamantri Ayushman Arogya Yojana (MAAY)",
    category: "Healthcare",
    state: "Rajasthan",
    ministry: "Govt. of Rajasthan",
    department: "Medical, Health & Family Welfare Department",
    short_description:
      "Up to ₹25 Lakh cashless healthcare coverage per family per year for inpatient medical and surgical treatments across empanelled hospitals.",
    benefits:
      "100% cashless hospitalization up to ₹25,00,000 per family per year with free coverage for NFSA, SECC, small farmers, and contractual workers.",
    documents: ["Jan Aadhaar Card", "Aadhaar Card of all family members"],
    apply_url: "https://health.rajasthan.gov.in/",
    official_website: "https://health.rajasthan.gov.in/",
    official_source_url: "https://health.rajasthan.gov.in/",
    tags: ["health", "cashless", "rajasthan", "hospitalization", "medical-cover"],
    min_age: 0,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Rajasthan"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-rj-palanhar",
    slug: "rj-palanhar-yojana",
    name: "Palanhar Yojana",
    category: "Children & Welfare",
    state: "Rajasthan",
    ministry: "Govt. of Rajasthan",
    department: "Social Justice and Empowerment Department",
    short_description:
      "Monthly financial aid of ₹1,500 to ₹2,500 per child plus ₹2,000 annual clothing allowance for orphans and children of destitute/widowed parents.",
    benefits:
      "₹1,500/month for children aged 0-6 and ₹2,500/month for school-going children aged 6-18, plus ₹2,000 annual grant for clothes, shoes, and school kits.",
    documents: [
      "Jan Aadhaar Card",
      "Child's birth certificate & school admission certificate",
      "Parent death/widow/disability certificate",
    ],
    apply_url: "https://sje.rajasthan.gov.in/",
    official_website: "https://sje.rajasthan.gov.in/",
    official_source_url: "https://sje.rajasthan.gov.in/",
    tags: ["children", "orphan", "widow-support", "rajasthan", "monthly-allowance"],
    min_age: 0,
    max_age: 18,
    gender: "any",
    max_annual_income: 120000,
    occupations: ["student", "any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Rajasthan"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Gujarat ---
  {
    id: "sch-gj-vahli-dikri",
    slug: "gj-vahli-dikri-yojana",
    name: "Vahli Dikri Yojana",
    category: "Women & Child Care",
    state: "Gujarat",
    ministry: "Govt. of Gujarat",
    department: "Women and Child Development Department",
    short_description:
      "₹1,10,000 total financial assistance in three stages for the first and second girl child of poor families to prevent female foeticide and promote education.",
    benefits:
      "₹4,000 upon Class 1 admission, ₹6,000 upon Class 9 admission, and ₹1,00,000 upon turning 18 for higher education or marriage.",
    documents: [
      "Girl child birth certificate",
      "Gujarat Domicile certificate",
      "Income certificate (< ₹2 Lakh)",
      "Aadhaar Card & Bank passbook",
    ],
    apply_url: "https://digitalgujarat.gov.in/",
    official_website: "https://digitalgujarat.gov.in/",
    official_source_url: "https://digitalgujarat.gov.in/",
    tags: ["girl-child", "gujarat", "education", "financial-grant", "women"],
    min_age: 0,
    max_age: 20,
    gender: "female",
    max_annual_income: 200000,
    occupations: ["student", "any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Gujarat"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Odisha ---
  {
    id: "sch-od-subhadra",
    slug: "od-subhadra-yojana",
    name: "Subhadra Yojana",
    category: "Women & Welfare",
    state: "Odisha",
    ministry: "Govt. of Odisha",
    department: "Women & Child Development Department",
    short_description:
      "₹50,000 total financial aid (₹10,000 per year for 5 years in two equal instalments on Rakhi Purnima and International Women's Day) for women aged 21 to 60 in Odisha.",
    benefits:
      "Direct benefit transfer of ₹10,000 every year directly to women's Aadhaar-enabled bank accounts, plus Subhadra debit card for digital transactions.",
    documents: [
      "Aadhaar card in applicant woman's name",
      "Mobile number linked with Aadhaar",
      "Single bank account linked with Aadhaar",
    ],
    apply_url: "https://subhadra.odisha.gov.in/",
    official_website: "https://subhadra.odisha.gov.in/",
    official_source_url: "https://subhadra.odisha.gov.in/",
    tags: ["women", "odisha", "dbt", "cash-assistance", "women-empowerment"],
    min_age: 21,
    max_age: 60,
    gender: "female",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Odisha"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-od-kalia",
    slug: "od-kalia-scheme",
    name: "KALIA Scheme (Krushak Assistance for Livelihood and Income Augmentation)",
    category: "Agriculture",
    state: "Odisha",
    ministry: "Govt. of Odisha",
    department: "Department of Agriculture and Farmers' Empowerment",
    short_description:
      "Financial assistance of ₹10,000 per year for small/marginal farmers and ₹12,500 livelihood package for landless agricultural households in Odisha.",
    benefits:
      "Direct cash assistance of ₹4,000 (Kharif) and ₹4,000 (Rabi) for crop cultivation, ₹12,500 for landless families for goat/duck/poultry rearing, and ₹2 Lakh life insurance.",
    documents: [
      "Aadhaar card",
      "Land records / Agricultural labourer certificate",
      "Ration card",
      "Bank passbook",
    ],
    apply_url: "https://kalia.odisha.gov.in/",
    official_website: "https://kalia.odisha.gov.in/",
    official_source_url: "https://kalia.odisha.gov.in/",
    tags: ["farmer", "odisha", "agriculture", "landless-labourer", "dbt"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["farmer", "labour"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "rural",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Odisha"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Madhya Pradesh ---
  {
    id: "sch-mp-ladli-behna",
    slug: "mp-mukhyamantri-ladli-behna-yojana",
    name: "Mukhyamantri Ladli Behna Yojana",
    category: "Women & Welfare",
    state: "Madhya Pradesh",
    ministry: "Govt. of Madhya Pradesh",
    department: "Women and Child Development Department",
    short_description:
      "₹1,250 monthly direct cash assistance into bank accounts of eligible women aged 21 to 60 residing in Madhya Pradesh.",
    benefits:
      "Direct cash transfer of ₹1,250 per month (₹15,000 per year) credited on the 10th of every month into beneficiary's Aadhaar-linked DBT account.",
    documents: [
      "Samagra ID (Family & Individual)",
      "Aadhaar Card linked with bank account and DBT enabled",
      "Active mobile number",
    ],
    apply_url: "https://cmladlibahna.mp.gov.in/",
    official_website: "https://cmladlibahna.mp.gov.in/",
    official_source_url: "https://cmladlibahna.mp.gov.in/",
    tags: ["women", "madhya-pradesh", "dbt", "cash-transfer", "welfare"],
    min_age: 21,
    max_age: 60,
    gender: "female",
    max_annual_income: 250000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Madhya Pradesh"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Delhi ---
  {
    id: "sch-dl-mahila-samman",
    slug: "delhi-mukhyamantri-mahila-samman-yojana",
    name: "Mukhyamantri Mahila Samman Yojana",
    category: "Women & Welfare",
    state: "Delhi",
    ministry: "Govt. of NCT of Delhi",
    department: "Women and Child Development Department",
    short_description:
      "₹1,000 monthly financial assistance for all adult women residents aged 18+ in Delhi who are not government employees or income tax payers.",
    benefits:
      "Monthly stipend of ₹1,000 directly transferred to eligible women to support daily individual expenses and enhance financial autonomy.",
    documents: [
      "Delhi Voter ID Card",
      "Aadhaar Card",
      "Bank passbook",
      "Self-declaration of not being an income tax payee",
    ],
    apply_url: "https://wcd.delhi.gov.in/",
    official_website: "https://wcd.delhi.gov.in/",
    official_source_url: "https://wcd.delhi.gov.in/",
    tags: ["women", "delhi", "monthly-stipend", "basic-income", "dbt"],
    min_age: 18,
    max_age: null,
    gender: "female",
    max_annual_income: 300000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "urban",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Delhi"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
  {
    id: "sch-dl-electricity-subsidy",
    slug: "delhi-domestic-electricity-subsidy",
    name: "Delhi Domestic Electricity Subsidy Scheme",
    category: "Energy & Utilities",
    state: "Delhi",
    ministry: "Govt. of NCT of Delhi",
    department: "Power Department",
    short_description:
      "100% free electricity up to 200 units per month, and 50% flat subsidy up to ₹800 for consumption between 201 and 400 units for domestic consumers in Delhi.",
    benefits:
      "Zero electricity bill for households using up to 200 units/month; substantial bill relief for middle-class families consuming up to 400 units/month.",
    documents: ["Delhi Electricity CA Number / Bill", "Mobile number linked with DISCOM"],
    apply_url: "https://delhi.gov.in/",
    official_website: "https://delhi.gov.in/",
    official_source_url: "https://delhi.gov.in/",
    tags: ["electricity", "free-power", "delhi", "subsidy", "utilities"],
    min_age: 18,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "urban",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Delhi"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Haryana ---
  {
    id: "sch-hr-old-age-samman",
    slug: "hr-old-age-samman-allowance",
    name: "Haryana Old Age Samman Allowance",
    category: "Pensions & Senior Citizens",
    state: "Haryana",
    ministry: "Govt. of Haryana",
    department: "Social Justice and Empowerment Department",
    short_description:
      "Generous monthly pension of ₹3,000 per month for all senior citizens aged 60+ residing in Haryana seamlessly verified via Parivar Pehchan Patra (PPP).",
    benefits:
      "Direct benefit transfer of ₹3,000/month credited without physical application upon turning 60 via Parivar Pehchan Patra database.",
    documents: [
      "Parivar Pehchan Patra (Family ID)",
      "Aadhaar Card",
      "Bank account linked with Aadhaar",
    ],
    apply_url: "https://socialjusticehry.gov.in/",
    official_website: "https://socialjusticehry.gov.in/",
    official_source_url: "https://socialjusticehry.gov.in/",
    tags: ["pension", "senior-citizen", "haryana", "ppp", "social-security"],
    min_age: 60,
    max_age: null,
    gender: "any",
    max_annual_income: 300000,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Haryana"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },

  // --- Punjab ---
  {
    id: "sch-pb-aam-aadmi-clinics",
    slug: "pb-aam-aadmi-clinics",
    name: "Aam Aadmi Clinics & Health Services",
    category: "Healthcare",
    state: "Punjab",
    ministry: "Govt. of Punjab",
    department: "Department of Health and Family Welfare",
    short_description:
      "100% free primary healthcare consultation, 80+ essential medicines, and 40+ clinical diagnostic tests at neighbourhood clinics across Punjab.",
    benefits:
      "Free doctor consultations, free generic medicines, free lab diagnostics (blood test, ECG, lipid profile), and digital health records for all citizens.",
    documents: ["Aadhaar card / Voter ID", "Mobile number"],
    apply_url: "https://health.punjab.gov.in/",
    official_website: "https://health.punjab.gov.in/",
    official_source_url: "https://health.punjab.gov.in/",
    tags: ["healthcare", "free-medicines", "free-tests", "punjab", "clinics"],
    min_age: 0,
    max_age: null,
    gender: "any",
    max_annual_income: null,
    occupations: ["any"],
    education_levels: [],
    caste_categories: [],
    disability_required: false,
    is_popular: true,
    area_type: "any",
    government_level: "State",
    scheme_scope: "STATE_ONLY",
    available_states: ["Punjab"],
    verification_status: "Verified",
    scheme_status: "Active",
    link_status: "ok",
    link_http_status: 200,
    link_fail_count: 0,
  },
];
