"""
Authentic, Verified Andhra Pradesh Government Welfare Schemes
Sourced from official Government of Andhra Pradesh portals:
- jnanabhumi.ap.gov.in (Higher Education & Scholarships)
- gsws.ap.gov.in (Grama Ward Sachivalayam & DBT Flagship Schemes)
- ysrrythubharosa.ap.gov.in (Agriculture & Farmer Income Support)
- ysraarogyasri.ap.gov.in (Cashless Healthcare & Aarogya Asara)
- sspensions.ap.gov.in (YSR / NTR Bharosa Social Security Pensions)
- ysrlawnestham.ap.gov.in (Junior Advocates Welfare)
- bocw.ap.gov.in (Building & Other Construction Workers Board)
- andhrabrahmin.ap.gov.in (Brahmin Welfare Corporation)
- apindustries.gov.in (MSME & Industrial Incentives)
- aptransport.org (Transport & Vahana Mitra)
- apsrtc.ap.gov.in (Women Free Bus Scheme)
"""

ANDHRA_PRADESH_VERIFIED_SCHEMES = [
    {
        "name": "Jagananna Vidya Deevena (RTF - Complete Fee Reimbursement)",
        "category": "Education & Scholarships",
        "ministry": "Higher Education & Social Welfare Department, Govt. of Andhra Pradesh",
        "department": "Department of Social Welfare",
        "short_description": "100% full tuition fee reimbursement for post-matric students from poor families pursuing Polytechnic, ITI, Degree, Engineering, Medicine, and PG courses in Andhra Pradesh.",
        "benefits": "Complete college tuition fee reimbursement paid directly to the mother's bank account in quarterly instalments, ensuring zero out-of-pocket academic expense for the student.",
        "min_age": 16,
        "max_age": 30,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["student"],
        "education_levels": ["secondary", "higher-secondary", "diploma", "graduate", "postgraduate"],
        "caste_categories": ["obc", "sc", "st", "ews", "minority"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://jnanabhumi.ap.gov.in/",
        "documents": [
            "Aadhaar card of student and mother",
            "White Ration Card / Rice Card issued by AP Civil Supplies",
            "Integrated Certificate (Caste, Nativity, Date of Birth) from MeeSeva / Grama Ward Sachivalayam",
            "Income Certificate issued by Tahsildar (< ₹2.5 Lakh)",
            "College Bonafide Certificate with Hall Ticket / Admission Number",
            "Mother's active bank passbook linked with Aadhaar (NPCI seeded)",
            "College Attendance Certificate (minimum 75% required)"
        ],
        "applicationProcedure": "Apply online through college login on JnanaBhumi portal (jnanabhumi.ap.gov.in) or enroll during the Navasakam beneficiary verification survey at your local Grama / Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "education", "scholarship", "college", "tuition-reimbursement", "student", "jnanabhumi"]
    },
    {
        "name": "Jagananna Vasathi Deevena (MTF - Boarding & Hostel Assistance)",
        "category": "Education & Scholarships",
        "ministry": "Higher Education & Social Welfare Department, Govt. of Andhra Pradesh",
        "department": "Department of Social Welfare",
        "short_description": "Financial assistance for food, boarding, and hostel expenses of post-matric students pursuing technical, professional, and degree education in Andhra Pradesh.",
        "benefits": "₹10,000 per year for ITI students, ₹15,000 per year for Polytechnic students, and ₹20,000 per year for Degree, Engineering, Pharmacy, and PG students in two instalments directly to mother's bank account.",
        "min_age": 16,
        "max_age": 30,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["student"],
        "education_levels": ["diploma", "graduate", "postgraduate"],
        "caste_categories": ["obc", "sc", "st", "ews", "minority"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://jnanabhumi.ap.gov.in/",
        "documents": [
            "Aadhaar card of student and mother",
            "White Ration Card / Rice Card",
            "Income Certificate (< ₹2.5 Lakh) from Tahsildar",
            "College Bonafide and Hostel Admission / Residence Certificate",
            "Mother's bank passbook linked with Aadhaar",
            "75% College Attendance record verified by Principal"
        ],
        "applicationProcedure": "Submitted simultaneously with Vidya Deevena through college verification on JnanaBhumi (jnanabhumi.ap.gov.in) with biometric authentication at Grama/Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "education", "hostel", "boarding", "scholarship", "student", "jnanabhumi"]
    },
    {
        "name": "Jagananna Amma Vodi / Thalliki Vandanam",
        "category": "Women & Child",
        "ministry": "School Education Department, Govt. of Andhra Pradesh",
        "department": "Department of School Education",
        "short_description": "Annual financial incentive to poor and needy mothers or recognized guardians who send their children to recognized schools or junior colleges from Class 1 to 12.",
        "benefits": "Direct financial assistance of ₹15,000 per academic year deposited directly into the unencumbered bank account of the mother to meet education expenses.",
        "min_age": 18,
        "max_age": 60,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar cards of mother and school-going child",
            "White Ration Card / Rice Card of Andhra Pradesh",
            "Child's Student Information Management System (SIMS) 14-digit Student ID",
            "School Bonafide Certificate showing 75% attendance",
            "Mother's bank passbook with Aadhaar linkage"
        ],
        "applicationProcedure": "Enrolled directly through school Headmaster validation on the Child Info SIMS portal followed by social audit verification at Grama / Ward Sachivalayams.",
        "tags": ["andhra-pradesh", "women", "children", "education", "amma-vodi", "school", "dbt"]
    },
    {
        "name": "YSR / NTR Bharosa Social Security Pension Scheme",
        "category": "Social Security & Pensions",
        "ministry": "Panchayat Raj & Rural Development Department, Govt. of Andhra Pradesh",
        "department": "Society for Elimination of Rural Poverty (SERP)",
        "short_description": "Monthly social security pension disbursed at the doorstep on the 1st of every month to senior citizens, destitute widows, weavers, fishermen, toddy tappers, single women, and chronic kidney disease patients.",
        "benefits": "₹4,000 per month for Old Age, Widow, Toddy Tapper, Weaver, Traditional Fishermen, and Single Women pensions; ₹6,000 per month for Disabled persons (40-79%); ₹15,000 per month for fully disabled/bedridden; ₹10,000 per month for Chronic Kidney Disease (CKDU) dialysis patients.",
        "min_age": 60,
        "max_age": None,
        "max_annual_income": 200000,
        "gender": "any",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://sspensions.ap.gov.in/",
        "documents": [
            "Aadhaar card of applicant",
            "White Ration Card / Rice Card of Andhra Pradesh",
            "Age proof (Birth Certificate / Voter ID / 10th marks card)",
            "Death Certificate of husband (for Widow Pension)",
            "UDID / SADAREM Medical Board Certificate (for Disability Pension)",
            "Government Nephrology Dialysis Passbook (for CKDU Pension)",
            "Aadhaar-seeded bank account / doorstep biometric verification"
        ],
        "applicationProcedure": "Submit application at your village / ward secretariat (Grama/Ward Sachivalayam) or online via sspensions.ap.gov.in for verification by the Welfare and Education Assistant.",
        "tags": ["andhra-pradesh", "pension", "senior-citizen", "widow", "social-security", "doorstep-pension", "sspensions"]
    },
    {
        "name": "YSR Rythu Bharosa - PM KISAN (Andhra Pradesh Farmer Input Support)",
        "category": "Agriculture",
        "ministry": "Agriculture & Cooperation Department, Govt. of Andhra Pradesh",
        "department": "Department of Agriculture",
        "short_description": "Financial input assistance of ₹13,500 per farmer family per year (inclusive of ₹6,000 PM-KISAN + ₹7,500 AP State share) for landholding farmer families and tenant farmers from SC/ST/BC/Minority categories cultivating ROFR lands.",
        "benefits": "₹13,500 per year transferred in three seasonal instalments: ₹7,500 in May (Kharif sowing preparation), ₹4,000 in October (Rabi crop care), and ₹2,000 in January (Sankranti harvesting).",
        "min_age": 18,
        "max_age": None,
        "max_annual_income": None,
        "gender": "any",
        "occupations": ["farmer"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "rural",
        "official_url": "https://ysrrythubharosa.ap.gov.in/",
        "documents": [
            "Aadhaar card of farmer",
            "Pattadar Passbook / 1B ROR / Webland digital revenue record",
            "Crop Cultivator Rights Card (CCRC) agreement (mandatory for tenant farmers)",
            "Aadhaar-seeded bank account with NPCI mapping",
            "e-Panta digital crop booking verification entry"
        ],
        "applicationProcedure": "Automatic verification through village agriculture assistants at Rythu Bharosa Kendras (RBKs) via Webland portal and e-Crop digital survey.",
        "tags": ["andhra-pradesh", "farmer", "agriculture", "rythu-bharosa", "dbt", "kisan", "crop-support"]
    },
    {
        "name": "Dr. YSR Aarogyasri / NTR Vaidya Seva Universal Health Scheme",
        "category": "Healthcare",
        "ministry": "Health, Medical and Family Welfare Department, Govt. of Andhra Pradesh",
        "department": "Dr. YSR Aarogyasri Health Care Trust",
        "short_description": "Flagship comprehensive cashless healthcare coverage for secondary and tertiary medical treatments covering 3,257 surgical and medical procedures up to ₹25 Lakh per family per year.",
        "benefits": "100% cashless medical and surgical treatment up to ₹25,00,000 per family per year across 2,400+ empaneled government and private hospitals in AP and metro cities (Hyderabad, Chennai, Bengaluru) including bed charges, surgery, ICU, and 10 days of post-discharge medicines.",
        "min_age": None,
        "max_age": None,
        "max_annual_income": 500000,
        "gender": "any",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://ysraarogyasri.ap.gov.in/",
        "documents": [
            "YSR Aarogyasri Health Card / White Ration Card (Rice Card)",
            "Aadhaar card of patient and family members",
            "Doctor clinical prescription / Hospital Aarogya Mithra helpdesk registration"
        ],
        "applicationProcedure": "Direct walk-in with Rice Card and Aadhaar card at the Aarogya Mithra helpdesk located at any empaneled government or private network hospital.",
        "tags": ["andhra-pradesh", "healthcare", "cashless", "aarogyasri", "hospital", "medical-insurance", "surgery"]
    },
    {
        "name": "YSR Aarogya Asara (Post-Operative Sustenance Allowance)",
        "category": "Healthcare",
        "ministry": "Health, Medical & Family Welfare Department, Govt. of Andhra Pradesh",
        "department": "Dr. YSR Aarogyasri Health Care Trust",
        "short_description": "Post-operative financial sustenance allowance provided to poor patients during the post-treatment rest and recuperation period to compensate for wage loss.",
        "benefits": "₹225 per day or up to ₹5,000 per month directly deposited into the patient's bank account upon discharge for designated surgical recovery periods.",
        "min_age": 18,
        "max_age": None,
        "max_annual_income": 500000,
        "gender": "any",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://ysraarogyasri.ap.gov.in/",
        "documents": [
            "Aarogyasri patient discharge summary with doctor's recommended rest period",
            "Aadhaar card of patient",
            "Bank passbook with Aadhaar linkage"
        ],
        "applicationProcedure": "Automatically processed by the Aarogya Mithra hospital coordinator upon patient discharge from an empaneled hospital.",
        "tags": ["andhra-pradesh", "healthcare", "wage-loss", "asara", "dbt", "post-operative"]
    },
    {
        "name": "YSR Cheyutha (Financial Empowerment for Women Aged 45-60)",
        "category": "Women & Child",
        "ministry": "Social Welfare & BC Welfare Departments, Govt. of Andhra Pradesh",
        "department": "Department of Backward Classes Welfare",
        "short_description": "Financial empowerment assistance of ₹75,000 over 4 years (₹18,750 per year) directly credited to poor women aged 45 to 60 years belonging to SC, ST, BC, and Minority communities to establish sustainable micro-enterprises.",
        "benefits": "₹18,750 per year DBT grant with technical handholding, bank tie-ups, and corporate linkages with Amul, Reliance, ITC, and P&G for sustainable livelihood ventures (dairy, retail, goat rearing).",
        "min_age": 45,
        "max_age": 60,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": ["obc", "sc", "st", "minority"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar card of woman applicant",
            "Integrated Caste Certificate (SC/ST/BC/Minority) from Tahsildar / MeeSeva",
            "White Ration Card / Rice Card of Andhra Pradesh",
            "Bank passbook with Aadhaar linkage",
            "Age proof (Birth Certificate / Voter ID / 10th marks memo verifying age 45-60)"
        ],
        "applicationProcedure": "Enrolled through the Navasakam field verification at local Grama / Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "women", "cheyutha", "bc-welfare", "sc-welfare", "st-welfare", "livelihood", "dbt"]
    },
    {
        "name": "YSR Aasara (DWCRA Women Loan Reimbursement)",
        "category": "Women & Child",
        "ministry": "Panchayat Raj & MEPMA, Govt. of Andhra Pradesh",
        "department": "Society for Elimination of Rural Poverty (SERP)",
        "short_description": "Reimbursement of the entire outstanding bank loan amount of DWCRA women Self Help Groups (SHGs) as of 11th April 2019 in four equal annual instalments directly to the individual bank accounts of SHG women members.",
        "benefits": "100% repayment of outstanding bank loan balance credited directly to each member's personal savings account.",
        "min_age": 18,
        "max_age": 70,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any", "self-employed"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar card of SHG member",
            "SHG Group Passbook & Member loan account details verified by VO / CO",
            "Rice Card",
            "Individual bank account passbook"
        ],
        "applicationProcedure": "Verified by SERP / MEPMA community coordinators and disbursed directly through Grama/Ward Sachivalayams.",
        "tags": ["andhra-pradesh", "women", "dwcra", "shg", "loan-reimbursement", "aasara"]
    },
    {
        "name": "YSR Sunna Vaddi (Zero Interest Loan Subsidy for Women SHGs)",
        "category": "Women & Child",
        "ministry": "Panchayat Raj & Rural Development, Govt. of Andhra Pradesh",
        "department": "SERP / MEPMA",
        "short_description": "Zero-interest loan scheme for rural and urban women SHGs where the government directly reimburses the entire bank interest charged on loans up to ₹3 Lakh to ₹5 Lakh.",
        "benefits": "100% bank interest reimbursement credited directly into SHG bank accounts upon prompt monthly loan repayment.",
        "min_age": 18,
        "max_age": 70,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["self-employed", "any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "SHG Bank Loan Passbook showing regular EMI repayments",
            "Member Aadhaar cards",
            "Bank verification statement of interest paid"
        ],
        "applicationProcedure": "Automated bank reconciliation via SERP/MEPMA portal; interest subsidy credited directly to qualifying SHG accounts.",
        "tags": ["andhra-pradesh", "women", "shg", "dwcra", "zero-interest", "sunna-vaddi"]
    },
    {
        "name": "YSR Sunna Vaddi Panta Runalu (Zero-Interest Crop Loans for Farmers)",
        "category": "Agriculture",
        "ministry": "Agriculture & Cooperation Department, Govt. of Andhra Pradesh",
        "department": "Department of Agriculture",
        "short_description": "Complete reimbursement of interest on crop loans up to ₹1,00,000 for all farmers in Andhra Pradesh who repay their seasonal crop loans within the stipulated 1-year timeline.",
        "benefits": "Zero percent interest on crop loans up to ₹1 Lakh with the interest component (approx. 4%) directly reimbursed into farmers' accounts via DBT.",
        "min_age": 18,
        "max_age": None,
        "max_annual_income": None,
        "gender": "any",
        "occupations": ["farmer"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "rural",
        "official_url": "https://ysrrythubharosa.ap.gov.in/",
        "documents": [
            "Pattadar Passbook / Webland extract",
            "Crop loan sanction and repayment statement from PACS or commercial bank",
            "e-Panta digital crop booking acknowledgment receipt",
            "Aadhaar card"
        ],
        "applicationProcedure": "Banks upload the list of farmers who repaid on time to the state agriculture portal; interest subsidy is credited via DBT.",
        "tags": ["andhra-pradesh", "farmer", "agriculture", "zero-interest", "crop-loan", "dbt"]
    },
    {
        "name": "YSR Kapu Nestham",
        "category": "Women & Child",
        "ministry": "Backward Classes Welfare Department, Govt. of Andhra Pradesh",
        "department": "Andhra Pradesh State Kapu Welfare and Development Corporation",
        "short_description": "Financial assistance of ₹60,000 to ₹75,000 (₹15,000 per year) to poor women aged 45 to 60 years belonging to Kapu, Balija, Telaga, and Ontari sub-castes to enhance their livelihood and economic status.",
        "benefits": "Direct credit of ₹15,000 per annum into beneficiary's bank account for setting up small livelihood units.",
        "min_age": 45,
        "max_age": 60,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": ["obc", "ews"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar card of applicant",
            "Integrated Community Certificate (Kapu / Balija / Telaga / Ontari) from Tahsildar",
            "White Ration Card / Rice Card",
            "Aadhaar-seeded bank passbook",
            "Age proof (voter ID / birth certificate showing age 45-60)"
        ],
        "applicationProcedure": "Apply online through Grama/Ward Sachivalayam during Navasakam or the GSWS citizen portal (gsws.ap.gov.in).",
        "tags": ["andhra-pradesh", "kapu", "women", "kapu-nestham", "livelihood", "dbt"]
    },
    {
        "name": "YSR EBC Nestham",
        "category": "Women & Child",
        "ministry": "Backward Classes Welfare Department, Govt. of Andhra Pradesh",
        "department": "Department of Backward Classes Welfare",
        "short_description": "Financial assistance of ₹45,000 (₹15,000 per year for 3 years) for economically backward class (EBC) women from Brahmin, Arya Vysya, Reddy, Kamma, Kshatriya, and other non-reserved open category poor families aged 45 to 60 years.",
        "benefits": "Direct cash transfer of ₹15,000 per year into the verified bank account of the beneficiary.",
        "min_age": 45,
        "max_age": 60,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": ["general", "ews"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar card",
            "Income Certificate (< ₹2.5 Lakh) from Tahsildar",
            "Integrated Certificate verifying non-reserved Open Category",
            "White Ration Card / Rice card",
            "Bank passbook with NPCI seeding",
            "Age proof (45-60 years)"
        ],
        "applicationProcedure": "Registered via Grama / Ward Sachivalayam survey and verified through Navasakam portal.",
        "tags": ["andhra-pradesh", "ebc", "women", "ebc-nestham", "dbt", "livelihood"]
    },
    {
        "name": "YSR Vahana Mitra",
        "category": "Social Security & Pensions",
        "ministry": "Transport, Roads & Buildings Department, Govt. of Andhra Pradesh",
        "department": "Transport Department",
        "short_description": "Annual financial allowance of ₹10,000 to self-employed driver-cum-owners of auto-rickshaws, light commercial motor cabs, and maxi-cabs for meeting vehicle fitness certification, insurance, and maintenance costs.",
        "benefits": "₹10,000 per year credited directly to the driver-cum-owner's bank account.",
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["self-employed", "labour", "any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://aptransport.org/",
        "documents": [
            "Aadhaar card of driver",
            "Valid Commercial Driving License",
            "Vehicle Registration Certificate (RC) in applicant's name",
            "Vehicle Fitness Certificate (FC) & Comprehensive Insurance policy",
            "White Ration Card / Rice Card",
            "Bank passbook"
        ],
        "applicationProcedure": "Apply online at aptransport.org or submit documents to the Motor Vehicles Inspector (MVI) via Grama/Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "auto-driver", "taxi", "transport", "vahana-mitra", "dbt"]
    },
    {
        "name": "YSR Nethanna Nestham",
        "category": "Business & MSME",
        "ministry": "Handlooms & Textiles Department, Govt. of Andhra Pradesh",
        "department": "Department of Handlooms and Textiles",
        "short_description": "Direct annual financial assistance of ₹24,000 per year to every handloom weaver family owning a working pit loom or frame loom to modernize their looms, procure high-quality yarn, and withstand competitive market pressures.",
        "benefits": "₹24,000 per year directly transferred to the weaver's bank account in a single instalment.",
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["artisan", "self-employed"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar card",
            "Handloom Geo-tagging Verification Certificate from Handlooms Department",
            "Weavers Cooperative Society ID or Handloom Registration",
            "White Ration Card / Rice card",
            "Bank passbook with Aadhaar linkage"
        ],
        "applicationProcedure": "Geo-tagging and field verification by Assistant Director of Handlooms followed by social audit at Grama/Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "weavers", "handloom", "nethanna-nestham", "textiles", "dbt"]
    },
    {
        "name": "YSR Matsyakara Bharosa (Fishermen Welfare & Ban Relief)",
        "category": "Agriculture",
        "ministry": "Animal Husbandry, Dairy Development & Fisheries Department, Govt. of AP",
        "department": "Department of Fisheries",
        "short_description": "Seasonal financial relief and welfare support to coastal and marine fishermen families during the 61-day annual fishing ban period, along with diesel subsidy and ex-gratia relief.",
        "benefits": "Direct financial assistance of ₹10,000 during the annual marine fishing ban period; enhanced diesel subsidy of ₹9 per litre for motorized and mechanized fishing boats; ex-gratia relief of ₹10,00,000 to the families of fishermen who die accidentally while fishing.",
        "min_age": 18,
        "max_age": 65,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["self-employed", "labour", "farmer"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://fisheries.ap.gov.in/",
        "documents": [
            "Aadhaar card",
            "Marine Fishermen Biometric ID Card / Boat Registration Certificate",
            "White Ration Card / Rice card",
            "Fisheries Department Verification Certificate",
            "Bank passbook"
        ],
        "applicationProcedure": "Registered through Fisheries Department field officers at coastal landing centres and verified via Grama/Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "fishermen", "marine", "fishing-ban", "matsyakara-bharosa", "dbt"]
    },
    {
        "name": "YSR Law Nestham (Junior Advocates Monthly Stipend)",
        "category": "Employment & Skill Development",
        "ministry": "Law and Justice Department, Govt. of Andhra Pradesh",
        "department": "Law Department",
        "short_description": "Monthly stipend to fresh law graduates during their initial three years of practice at the Bar to encourage young advocates from humble backgrounds.",
        "benefits": "Monthly stipend of ₹5,000 to ₹10,000 per month credited directly to the junior advocate's bank account for up to 3 years.",
        "min_age": 21,
        "max_age": 35,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["self-employed", "unemployed", "any"],
        "education_levels": ["graduate", "postgraduate"],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://ysrlawnestham.ap.gov.in/",
        "documents": [
            "Bar Council of Andhra Pradesh Enrollment Certificate",
            "All India Bar Examination (AIBE) Certificate",
            "Law Degree (LL.B / B.L.) Provisional / Original Degree Certificate",
            "Attestation certificate from Senior Advocate having 15+ years experience",
            "White Ration Card / Rice Card",
            "Aadhaar card and Bank passbook"
        ],
        "applicationProcedure": "Apply online at ysrlawnestham.ap.gov.in with scanned Bar Council credentials and senior advocate certificate.",
        "tags": ["andhra-pradesh", "lawyers", "advocates", "stipend", "law-nestham", "youth"]
    },
    {
        "name": "YSR Jagananna Chedodu",
        "category": "Financial Assistance",
        "ministry": "Backward Classes Welfare Department, Govt. of Andhra Pradesh",
        "department": "Department of Backward Classes Welfare",
        "short_description": "Annual financial assistance of ₹10,000 per year to small business service providers including Rajakas (washermen), Nayee Brahmins (barbers), and Tailors to invest in modern equipment, tools, and consumables.",
        "benefits": "₹10,000 per annum direct cash transfer into bank account to procure modern tools, scissors, steam irons, and styling equipment.",
        "min_age": 21,
        "max_age": 60,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["artisan", "self-employed"],
        "education_levels": [],
        "caste_categories": ["obc"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Aadhaar card",
            "Trade / Community Certificate (Rajaka / Nayee Brahmin / Tailor) from Tahsildar",
            "Shop Establishment / Tool verification certificate by Ward/Grama Volunteer",
            "White Ration Card / Rice card",
            "Bank passbook"
        ],
        "applicationProcedure": "Field verification by Welfare & Education Assistant at Grama / Ward Sachivalayam.",
        "tags": ["andhra-pradesh", "barbers", "washermen", "tailors", "bc-welfare", "chedodu", "dbt"]
    },
    {
        "name": "YSR Bima (Universal Breadwinner Insurance Relief)",
        "category": "Social Security & Pensions",
        "ministry": "Labour, Factories & Boilers Department, Govt. of Andhra Pradesh",
        "department": "Department of Labour",
        "short_description": "100% state-funded accident and life insurance coverage for the primary earning member (breadwinner) of all poor, unorganised, and BPL households in Andhra Pradesh.",
        "benefits": "₹5,00,000 financial relief for accidental death or permanent total disability (age 18-70); immediate funeral assistance of ₹10,000 provided within 24 hours of demise directly to the nominee.",
        "min_age": 18,
        "max_age": 70,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["labour", "unorganised-worker", "farmer", "self-employed", "any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://ysrbima.ap.gov.in/",
        "documents": [
            "Aadhaar card of primary breadwinner and nominated family member",
            "White Ration Card / Rice Card",
            "Nominee's bank passbook",
            "Death Certificate / FIR copy / Medical certificate (in case of claim settlement)"
        ],
        "applicationProcedure": "Enrolled door-to-door by village volunteers; claims processed within 24 hours by Grama/Ward Sachivalayam staff.",
        "tags": ["andhra-pradesh", "insurance", "accidental-death", "bima", "labour", "social-security"]
    },
    {
        "name": "YSR Kalyanamasthu & YSR Shaadi Tohfa",
        "category": "Women & Child",
        "ministry": "Social Welfare, BC, Minority & Divyangjan Departments, Govt. of AP",
        "department": "Department of Social Welfare",
        "short_description": "Direct financial assistance for the marriage of poor daughters from SC, ST, BC, Minority, and Divyangjan families, with mandatory requirement of Class 10 qualification to eliminate child marriage.",
        "benefits": "₹1,00,000 for SC/ST; ₹1,20,000 for SC/ST Inter-caste; ₹50,000 for BC; ₹75,000 for BC Inter-caste; ₹1,00,000 for Minorities (Shaadi Tohfa); ₹1,50,000 for Divyangjan marriages.",
        "min_age": 18,
        "max_age": 40,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": ["secondary", "higher-secondary", "diploma", "graduate", "postgraduate"],
        "caste_categories": ["obc", "sc", "st", "minority"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://gsws.ap.gov.in/",
        "documents": [
            "Class 10 (SSC) Pass Certificate of BOTH Bride and Groom (mandatory qualification)",
            "Aadhaar cards of Bride and Groom",
            "Marriage Registration Certificate issued by Sub-Registrar / Village Registrar",
            "Integrated Caste & Income Certificates from MeeSeva",
            "White Ration Card / Rice card",
            "Bride's bank passbook with Aadhaar linkage"
        ],
        "applicationProcedure": "Apply online at gsws.ap.gov.in within 60 days of solemnization of marriage with joint biometric authentication.",
        "tags": ["andhra-pradesh", "marriage-assistance", "kalyanamasthu", "shaadi-tohfa", "women", "dbt"]
    },
    {
        "name": "AP Divyangjan (Disability) Pension & Mobility Welfare",
        "category": "Disability & Inclusion",
        "ministry": "Women, Children, Differently Abled and Senior Citizens Department, Govt. of AP",
        "department": "Department for the Welfare of Persons with Disabilities",
        "short_description": "Enhanced monthly disability pension of ₹6,000 to ₹15,000 per month and free motorized retrofitted tricycles, battery wheelchairs, and assistive devices for persons with benchmark disabilities.",
        "benefits": "₹6,000/month for persons with 40% to 79% disability; ₹15,000/month for bedridden individuals or severe multi-disabilities; free motorized retrofitted tricycle worth ₹65,000.",
        "min_age": 5,
        "max_age": None,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": true,
        "area_type": "any",
        "official_url": "https://sspensions.ap.gov.in/",
        "documents": [
            "SADAREM / UDID Disability Certificate (40%+ benchmark disability)",
            "Aadhaar card of applicant",
            "White Ration Card / Rice card",
            "Bank passbook with Aadhaar linkage"
        ],
        "applicationProcedure": "Apply at Grama / Ward Sachivalayam with SADAREM certificate number for doorstep monthly pension disbursement.",
        "tags": ["andhra-pradesh", "disability", "divyangjan", "sadarem", "pension", "tricycle", "mobility"]
    },
    {
        "name": "Jagananna Videshi Vidya Deevena (Overseas Education Grant)",
        "category": "Education & Scholarships",
        "ministry": "Social Welfare, BC & Minority Welfare Departments, Govt. of AP",
        "department": "Department of Social Welfare",
        "short_description": "Financial grant up to ₹1.25 Crore for meritorious SC, ST, BC, Minority, and EBC students from Andhra Pradesh securing admission in top 100 QS World Ranking universities abroad.",
        "benefits": "100% tuition fee reimbursement up to ₹1.25 Crore for top 1 to 50 QS ranked institutions; up to ₹1.00 Crore for 51 to 100 QS ranked institutions covering visa, airfare, and course fees.",
        "min_age": 20,
        "max_age": 35,
        "max_annual_income": 800000,
        "gender": "any",
        "occupations": ["student"],
        "education_levels": ["graduate", "postgraduate"],
        "caste_categories": ["obc", "sc", "st", "ews", "minority"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://jnanabhumi.ap.gov.in/",
        "documents": [
            "Unconditional Offer Letter from Top 100 QS World Ranked University",
            "GRE / GMAT / TOEFL / IELTS qualifying score card",
            "All undergraduate degree marks memos and provisional certificates",
            "Integrated Caste Certificate and Income Certificate (< ₹8 Lakh)",
            "Valid Indian Passport and Student Visa",
            "Aadhaar card and Nationalized Bank Account details"
        ],
        "applicationProcedure": "Apply online at jnanabhumi.ap.gov.in; selection evaluated by State Level Screening Committee headed by Principal Secretary.",
        "tags": ["andhra-pradesh", "overseas-education", "foreign-scholarship", "jnanabhumi", "higher-studies"]
    },
    {
        "name": "Deepam 2.0 Free LPG Cylinder Scheme (Super Six)",
        "category": "Women & Child",
        "ministry": "Consumer Affairs, Food & Civil Supplies Department, Govt. of Andhra Pradesh",
        "department": "Civil Supplies Department",
        "short_description": "Provision of 3 free domestic LPG cooking gas cylinder refills per financial year (one cylinder every 4 months) to all eligible BPL household women in Andhra Pradesh.",
        "benefits": "100% refund of domestic LPG cylinder cost transferred directly via DBT into the beneficiary woman's bank account within 48 hours of delivery.",
        "min_age": 18,
        "max_age": None,
        "max_annual_income": 250000,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://civilsupplies.ap.gov.in/",
        "documents": [
            "White Ration Card / Rice Card of Andhra Pradesh",
            "Aadhaar card of female head of household",
            "Active domestic LPG Consumer Number (IOCL / HPCL / BPCL)",
            "NPCI Aadhaar-seeded bank account passbook"
        ],
        "applicationProcedure": "Book LPG cylinder with your regular gas distributor; subsidy is credited automatically into Aadhaar-linked bank account within 2 business days.",
        "tags": ["andhra-pradesh", "women", "lpg", "deepam", "free-gas", "super-six", "dbt"]
    },
    {
        "name": "AP Free Agricultural Power Supply Scheme (9 Hours Daytime Power)",
        "category": "Agriculture",
        "ministry": "Energy Department, Govt. of Andhra Pradesh",
        "department": "APSPDCL & APEPDCL",
        "short_description": "Free, uninterrupted 9-hours daytime three-phase electric power supply to all registered agricultural pumpsets across Andhra Pradesh.",
        "benefits": "100% free electricity power supply up to 9 hours daily during daylight hours for all agricultural pump connections, saving farmers up to ₹40,000 annually.",
        "min_age": 18,
        "max_age": None,
        "max_annual_income": None,
        "gender": "any",
        "occupations": ["farmer"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "rural",
        "official_url": "https://www.apspdcl.in/",
        "documents": [
            "Pattadar Passbook / Land title deed",
            "Agricultural Electricity Service Connection Consumer Number (USC)",
            "Aadhaar card of farmer"
        ],
        "applicationProcedure": "Handled through local DISCOM electricity revenue offices and Rythu Bharosa Kendras (RBKs).",
        "tags": ["andhra-pradesh", "farmer", "agriculture", "free-power", "irrigation", "electricity"]
    },
    {
        "name": "Anna Canteens (Subsidized Wholesome Meals at ₹5)",
        "category": "Social Security & Pensions",
        "ministry": "Municipal Administration & Urban Development Department, Govt. of Andhra Pradesh",
        "department": "Commissioner & Director of Municipal Administration (CDMA)",
        "short_description": "Statewide network of subsidized hygienic urban food canteens serving nutritious breakfast, lunch, and dinner to labourers, students, daily-wage workers, and attendants of hospital patients at just ₹5 per meal.",
        "benefits": "Nutritious breakfast (idli/upma/dosa) at ₹5; hot wholesome lunch and dinner (rice, sambar, dal, curry, curd) at ₹5 per plate in clean air-conditioned canteens.",
        "min_age": None,
        "max_age": None,
        "max_annual_income": None,
        "gender": "any",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://cdma.ap.gov.in/",
        "documents": [
            "No documents required; token coupon available directly at canteen counters"
        ],
        "applicationProcedure": "Walk in directly to any Anna Canteen across all municipal corporations and towns in Andhra Pradesh.",
        "tags": ["andhra-pradesh", "food-security", "anna-canteens", "subsidized-meal", "labour", "students"]
    },
    {
        "name": "AP Building & Other Construction Workers (BOCW) Welfare Schemes",
        "category": "Social Security & Pensions",
        "ministry": "Labour, Factories, Boilers & Insurance Medical Services Department, Govt. of AP",
        "department": "AP Building and Other Construction Workers Welfare Board",
        "short_description": "Statutory welfare assistance covering maternity grants, fatal accident compensation, daughter's marriage grant, toolkits, and children's education scholarships for registered construction workers.",
        "benefits": "₹20,000 maternity assistance for female workers; ₹5,00,000 ex-gratia for workplace accidental death; ₹50,000 daughter marriage grant; scholarships up to ₹25,000/yr for engineering/medical studies; free modern toolkits.",
        "min_age": 18,
        "max_age": 60,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["labour", "unorganised-worker"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://bocw.ap.gov.in/",
        "documents": [
            "AP BOCW Labour Board Registration Identity Card / Shramik Card",
            "90-day construction work proof from registered civil contractor / Gram Panchayat",
            "Aadhaar card",
            "Bank passbook"
        ],
        "applicationProcedure": "Register online at bocw.ap.gov.in or through Assistant Labour Officer at District Labour Offices.",
        "tags": ["andhra-pradesh", "construction-workers", "labour", "bocw", "welfare", "scholarship"]
    },
    {
        "name": "AP Brahmin Welfare Corporation Schemes (Gayatri, Bharati, Chanakya)",
        "category": "SC/ST/OBC Welfare",
        "ministry": "Backward Classes Welfare Department, Govt. of Andhra Pradesh",
        "department": "Andhra Pradesh Brahmin Welfare Corporation Limited",
        "short_description": "Integrated education, skill development, entrepreneurship, and welfare support for economically disadvantaged Brahmin families in Andhra Pradesh.",
        "benefits": "Gayatri Vidya Prasasthi cash awards for top ranks (₹10,000 - ₹20,000); Bharati Vidya Nidhi monthly scholarships; Chanakya self-employment loan margin grants up to ₹3,00,000.",
        "min_age": 6,
        "max_age": 55,
        "max_annual_income": 250000,
        "gender": "any",
        "occupations": ["any", "student", "self-employed"],
        "education_levels": [],
        "caste_categories": ["general", "ews"],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://www.andhrabrahmin.ap.gov.in/",
        "documents": [
            "Brahmin Community Certificate issued by Tahsildar / MeeSeva",
            "Income Certificate (< ₹2.5 Lakh) or White Ration Card",
            "Academic marks memo / Bonafide certificate",
            "Aadhaar card and Bank passbook"
        ],
        "applicationProcedure": "Apply online at andhrabrahmin.ap.gov.in; sanctions processed directly to bank accounts via DBT.",
        "tags": ["andhra-pradesh", "brahmin", "corporation", "scholarship", "chanakya", "gayatri"]
    },
    {
        "name": "AP Free Public Bus Travel Scheme for Women (Maha Sakthi)",
        "category": "Women & Child",
        "ministry": "Transport, Roads and Buildings Department, Govt. of Andhra Pradesh",
        "department": "Andhra Pradesh State Road Transport Corporation (APRTC)",
        "short_description": "Free zero-ticket bus travel for all domicile women, girls, and transgender persons in all Andhra Pradesh State Road Transport Corporation (APSRTC) Palle Velugu and Ultra Palle Velugu rural and city buses.",
        "benefits": "100% zero-fare bus travel across all district, city, and rural APSRTC bus routes on showing any valid domicile government identity card.",
        "min_age": None,
        "max_age": None,
        "max_annual_income": None,
        "gender": "female",
        "occupations": ["any"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://www.apsrtc.ap.gov.in/",
        "documents": [
            "Aadhaar card / Voter ID / Resident Identity card showing Andhra Pradesh address"
        ],
        "applicationProcedure": "Direct zero-fare ticket issued by bus conductor on boarding APSRTC Palle Velugu / City Ordinary buses upon presenting valid ID.",
        "tags": ["andhra-pradesh", "women", "free-bus", "apsrtc", "maha-sakthi", "transport"]
    },
    {
        "name": "AP MSME Policy Incentives & Industrial Subsidies",
        "category": "Business & MSME",
        "ministry": "Industries & Commerce Department, Govt. of Andhra Pradesh",
        "department": "Directorate of Industries",
        "short_description": "Fiscal incentives, 100% stamp duty reimbursement, 15% to 45% capital investment subsidy, and power tariff concessions for micro and small enterprises set up in Andhra Pradesh.",
        "benefits": "15% to 25% investment subsidy up to ₹30 Lakh for general enterprises (45% up to ₹50 Lakh for SC/ST and Women entrepreneurs); ₹1.00 per unit power subsidy for 5 years; 100% net SGST reimbursement.",
        "min_age": 21,
        "max_age": 65,
        "max_annual_income": None,
        "gender": "any",
        "occupations": ["entrepreneur", "self-employed"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "any",
        "official_url": "https://apindustries.gov.in/",
        "documents": [
            "Udyam Registration Certificate",
            "Project Cost Report certified by Chartered Accountant",
            "Industrial land registration / lease document",
            "Bank term loan sanction & disbursement letter",
            "Pollution Control Board Consent and electricity energization bill"
        ],
        "applicationProcedure": "Apply online via the AP Single Desk Portal (apindustries.gov.in); approvals granted within 21 days under statutory service guarantee.",
        "tags": ["andhra-pradesh", "msme", "business", "subsidy", "industry", "entrepreneur", "single-desk"]
    },
    {
        "name": "YSR Free Crop Insurance (Sunna Vaddi Panta Bima)",
        "category": "Agriculture",
        "ministry": "Agriculture & Cooperation Department, Govt. of Andhra Pradesh",
        "department": "Department of Agriculture",
        "short_description": "Universal free crop insurance for all notified seasonal crops where the entire farmer's premium share is paid by the Government of Andhra Pradesh.",
        "benefits": "Zero-premium crop insurance for farmers with automatic enrollment based on e-Panta crop booking records, guaranteeing direct compensation for crop loss due to drought, cyclone, or pests.",
        "min_age": 18,
        "max_age": None,
        "max_annual_income": None,
        "gender": "any",
        "occupations": ["farmer"],
        "education_levels": [],
        "caste_categories": [],
        "disability_required": false,
        "area_type": "rural",
        "official_url": "https://karshak.ap.gov.in/",
        "documents": [
            "Aadhaar card",
            "e-Panta digital crop entry receipt from RBK",
            "Pattadar Passbook / Webland ROR",
            "Bank account linked with NPCI"
        ],
        "applicationProcedure": "Automatic enrollment through e-Crop digital verification at Rythu Bharosa Kendras; zero premium paid by the farmer.",
        "tags": ["andhra-pradesh", "farmer", "crop-insurance", "panta-bima", "agriculture", "free-insurance"]
    }
]
